-- The amenity vocabulary: every token already bound to a shipped icon.
insert into cms.amenities (token, name_en, name_ar, icon, sort_order)
select * from (values
  ('app','Community app','تطبيق للمجتمع','am_app',0),
  ('bab_beach','3.5 km beachfront','شاطئ ٣٫٥ كم','am_beach',1),
  ('bab_community','Community living','حياة مجتمعية','am_community',2),
  ('bab_finished','Fully finished units','وحدات كاملة التشطيب','am_finished',3),
  ('bab_fnb','F&B tenants','مطاعم ومقاهي','am_dining',4),
  ('bab_heart','In the heart of Sidi Heneish','في قلب سيدي حنيش','pin',5),
  ('bab_hotels','Four hotels','أربعة فنادق','am_hotel',6),
  ('bab_lagoons','Swimmable lagoons','بحيرات للسباحة','am_lagoon',7),
  ('bab_landscape','Landscape','لاندسكيب','am_landscape',8),
  ('beach','Private beach','شاطئ خاص','am_beach',9),
  ('bms','Smart buildings (BMS)','مبانٍ ذكية (BMS)','am_bms',10),
  ('cctv','CCTV with AI','مراقبة بالذكاء الاصطناعي','am_cctv',11),
  ('centralpark','Central park','حديقة مركزية','am_centralpark',12),
  ('clinic','Medical center','مركز طبي','am_clinic',13),
  ('clubhouse','Clubhouse','كلوب هاوس','am_club',14),
  ('clubsports','Clubhouse & sports facilities','كلوب هاوس ومرافق رياضية','am_club',15),
  ('commercialpark','Commercial park','بارك تجاري','am_pavilion',16),
  ('concierge','Lobbies & concierge','لوبيهات وكونسيرج','am_concierge',17),
  ('controls','Automated controls','تحكّم آلي','am_controls',18),
  ('d5campus','District 5 Campus','كامباس ديستريكت ٥','am_campus',19),
  ('d5club','District 5 Club','نادي ديستريكت ٥','am_club',20),
  ('d5m','D5M shopping mall','مول D5M','am_retail',21),
  ('eco','Green & eco-friendly','أخضر وصديق للبيئة','am_eco',22),
  ('ev','Car charging stations','محطات شحن سيارات','am_ev',23),
  ('fiber','Fibre optic, triple play','ألياف بصرية ثلاثية الخدمة','am_fiber',24),
  ('gardenparks','Street-side garden parks','حدائق على جانبي الشوارع','am_gardenpark',25),
  ('generators','Backup generators','مولّدات احتياطية','am_power',26),
  ('greenspine','Extended green spine & paseo','عمود أخضر ممتد وباسيو','am_paseo',27),
  ('gym','Gym & fitness','جيم ولياقة','am_gym',28),
  ('heat','Heat detection','أنظمة كشف حراري','am_heat',29),
  ('housekeeping','Hospitality services','خدمات ضيافة','am_laundry',30),
  ('kids','Kids areas','مناطق أطفال','am_kids',31),
  ('lagoon','Crystal lagoons','بحيرات كريستالية','am_lagoon',32),
  ('landscape','Green landscapes','مساحات خضراء','am_landscape',33),
  ('lifestylearea','Lifestyle Area','منطقة اللايف ستايل','am_lifestyle',34),
  ('mb_beach','Sandy beaches','شواطئ رملية','am_beach',35),
  ('mb_beachsvc','Beach food & service','خدمة وطعام على الشاطئ','am_dining',36),
  ('mb_bikes','Bike paths','مسارات دراجات','am_sports',37),
  ('mb_guards','Lifeguarded lagoons','منقذون على البحيرات','am_security',38),
  ('mb_gym','Fitness facility','مركز لياقة','am_gym',39),
  ('mb_lagoons','Five swimmable lagoons','خمس بحيرات للسباحة','am_lagoon',40),
  ('mb_retail','20+ shops & restaurants','أكثر من ٢٠ متجراً ومطعماً','am_retail',41),
  ('mb_spine','Botanical spine & garden','عمود أخضر وحديقة نباتية','am_paseo',42),
  ('mindhaus','District 5 Mindhaus offices','مكاتب مايندهاوس','am_office',43),
  ('mosque','Mosque','مسجد','am_mosque',44),
  ('ms_41_dining','Cafe & restaurant','كافيه ومطعم','am_dining',45),
  ('ms_41_gym','Gym & sports','جيم ورياضة','am_gym',46),
  ('ms_41_offices','Office & clinic spaces','مساحات مكاتب وعيادات','am_office',47),
  ('ms_41_retail','Bank, market, jewellery & furniture','بنك وسوق ومجوهرات وأثاث','am_retail',48),
  ('ms_beachclub','Barbarossa Beach Club & restaurant','نادي بربروسا الشاطئي ومطعمه','am_club',49),
  ('ms_beachsports','Beach bar, sports & activities','بار الشاطئ ورياضاته وأنشطته','am_beach',50),
  ('ms_cabanas','Marmarica Boutique Cabanas — 18 cabanas','كابانات مرماريكا البوتيكية — ١٨ كابانا','am_hotel',51),
  ('ms_downtown','Downtown clubhouse','كلوب هاوس الداون تاون','am_club',52),
  ('ms_kids','Kids area','منطقة أطفال','am_kids',53),
  ('ms_lagoons','Lagoons','بحيرات','am_lagoon',54),
  ('ms_mist_cafe','Lake cafe','كافيه البحيرة','am_dining',55),
  ('ms_mist_calm','Sitting, relaxation & meditation areas','أماكن جلوس واسترخاء وتأمّل','am_yoga',56),
  ('ms_mist_gym','Gym, club house & outdoor gym','جيم وكلوب هاوس وجيم خارجي','am_gym',57),
  ('ms_mist_kids','Nursery, kids area & kids node','حضانة ومنطقة أطفال وركن أطفال','am_kids',58),
  ('ms_mist_pets','Pets park','حديقة الحيوانات الأليفة','am_flower',59),
  ('ms_mist_plaza','Main plaza','البلازا الرئيسية','am_pavilion',60),
  ('ms_mist_promenade','Promenade & deck','بروميناد وممشى خشبي','am_paseo',61),
  ('ms_mist_serviced','Serviced apartments','شقق فندقية','am_hotel',62),
  ('ms_mist_sports','Sports area & outdoor fitness','منطقة رياضية ولياقة في الهواء الطلق','am_sports',63),
  ('ms_mist_water','Water deck, waterfront platforms & lakes','ممشى مائي ومنصات على الماء وبحيرات','am_lagoon',64),
  ('ms_mosque','Mosque','مسجد','am_mosque',65),
  ('ms_padel','Sports & courts, padel tennis by JPadel','ملاعب ورياضات، وبادل مع JPadel','am_sports',66),
  ('ms_peppermint','Peppermint wellbeing centre','مركز بيبرمنت للعافية','am_sauna',67),
  ('ms_ritsa','Ritsa commercial area','منطقة ريتسا التجارية','am_retail',68),
  ('ms_trio_club','Club house & commercial strip','كلوب هاوس وشريط تجاري','am_club',69),
  ('ms_trio_fit','Fitness zone','منطقة لياقة','am_gym',70),
  ('ms_trio_gardens','Hanging gardens & flying pools','حدائق معلّقة وحمامات سباحة طائرة','am_gardenpark',71),
  ('ms_trio_kids','Kids play zone','منطقة لعب للأطفال','am_kids',72),
  ('ms_trio_privacy','Three villas per complex, private gardens','ثلاث فيلات لكل مجمّع بحدائق خاصة','am_community',73),
  ('ms_trio_read','Reading & work station','ركن قراءة وعمل','am_office',74),
  ('ms_trio_seat','Seating areas','أماكن جلوس','am_flower',75),
  ('ms_trio_yoga','Yoga garden & meditation zone','حديقة يوجا ومنطقة تأمّل','am_yoga',76),
  ('ms_w31_admin','Administration building','مبنى إداري','am_office',77),
  ('ms_w31_calm','Meditation zone & relaxing area','منطقة تأمّل ومكان استرخاء','am_yoga',78),
  ('ms_w31_club','Club house','كلوب هاوس','am_club',79),
  ('ms_w31_fnb','F&B outlets & lake cafe','مطاعم ومقاهٍ وكافيه البحيرة','am_dining',80),
  ('ms_w31_jog','Jogging track & workout area','مضمار جري ومنطقة تمارين','am_sports',81),
  ('ms_w31_kids','Kids play zone & cafe','منطقة لعب أطفال وكافيه','am_kids',82),
  ('ms_w31_lake','Lake & grand water features','بحيرة ومسطحات مائية كبرى','am_lagoon',83),
  ('ms_w31_pets','Pets zone & multipurpose area','منطقة حيوانات أليفة ومساحة متعددة الاستخدامات','am_flower',84),
  ('neighborhoodpark','Neighborhood park','حديقة الحي','am_flower',85),
  ('nursery','Nursery & kids play','حضانة ولعب أطفال','am_kids',86),
  ('outdoorfit','Yoga & outdoor fitness','يوجا ولياقة في الهواء الطلق','am_yoga',87),
  ('parking','Cashless parking','موقف بلا نقد','am_parking',88),
  ('pool','Swimming pools','حمامات سباحة','am_pool',89),
  ('retail','Retail & dining','محلات ومطاعم','am_retail',90),
  ('sauna','Sauna','ساونا','am_sauna',91),
  ('security','24/7 security','أمن على مدار الساعة','am_security',92),
  ('sports','Sports & tracks','ملاعب ومسارات','am_sports',93),
  ('ss_beach','1 km of beach front','واجهة شاطئية بطول كيلومتر','am_beach',94),
  ('ss_clubs','Four clubhouses','أربعة كلوب هاوس','am_club',95),
  ('ss_hospital','Hospital','مستشفى','am_clinic',96),
  ('ss_hotels','Two hotels','فندقان','am_hotel',97),
  ('ss_lagoons','88,000 m² of swimmable lagoons','٨٨٬٠٠٠ م² من البحيرات القابلة للسباحة','am_lagoon',98),
  ('ss_land','503 acres, masterplanned by WATG','٥٠٣ أفدنة بمخطط عام من WATG','masterplan',99),
  ('ss_piazza','Piazza','بيازا','am_pavilion',100),
  ('ss_retail','High-end retail','محال تجارية راقية','am_retail',101),
  ('sw_center','Community centre','مركز مجتمعي','am_community',102),
  ('sw_clinics','Clinics','عيادات','am_clinic',103),
  ('sw_club','Clubhouse — 10,000 m²','كلوب هاوس — ١٠٬٠٠٠ م²','am_club',104),
  ('sw_daycare','Daycare','حضانة','am_kids',105),
  ('sw_entertainment','Entertainment','ترفيه','am_lifestyle',106),
  ('sw_ev','Electric charging','شحن كهربائي','am_ev',107),
  ('sw_football','Football club — 130,000 m²','نادٍ لكرة القدم — ١٣٠٬٠٠٠ م²','am_sports',108),
  ('sw_lanes','Bike & running lanes','مسارات دراجات وجري','am_paseo',109),
  ('sw_parks','Parks & water features','حدائق ومسطحات مائية','am_gardenpark',110),
  ('sw_retail','Community retail — 5,000 m²','تجزئة الحي — ٥٬٠٠٠ م²','am_retail',111),
  ('sw_school','School — 20,000 m²','مدرسة — ٢٠٬٠٠٠ م²','am_campus',112),
  ('sw_serviced','Serviced apartments','شقق فندقية','am_hotel',113),
  ('urbanehotel','Urbane Hotel','فندق أوربان','am_hotel',114),
  ('ze_clinics','Medical clinics','عيادات طبية','am_clinic',115),
  ('ze_club','ZED Sports Club — 43 acres','نادي زيد الرياضي — ٤٣ فداناً','am_sports',116),
  ('ze_concierge','Concierge, resident & furniture lifts','كونسيرج ومصعدا سكان وأثاث','am_concierge',117),
  ('ze_finished','Delivered fully finished, including ACs','تُسلَّم كاملة التشطيب بما فيها التكييف','am_finished',118),
  ('ze_mall','Shopping mall, retail & F&B','مول ومحال ومطاعم','am_retail',119),
  ('ze_office','Office park','مجمّع مكاتب','am_office',120),
  ('ze_park','Eight acres of central landscape','ثمانية أفدنة من الحديقة المركزية','am_centralpark',121),
  ('ze_parking','Underground parking','جراج تحت الأرض','am_parking',122),
  ('zw_finished','Fully finished with ACs & imported kitchens','تشطيب كامل مع تكييفات ومطابخ مستوردة','am_finished',123),
  ('zw_kids','Kids area & barbecue area','منطقة أطفال ومنطقة شواء','am_kids',124),
  ('zw_lifestyle','Theatre, zipline & the ZED Winter Festival','مسرح وزيبلاين ومهرجان زيد الشتوي','am_lifestyle',125),
  ('zw_mall','High-end mall & the Italiano restaurant','مول راقٍ ومطعم إيتاليانو','am_retail',126),
  ('zw_offices','77,100 m² of offices & clinics','٧٧٬١٠٠ م² من المكاتب والعيادات','am_office',127),
  ('zw_park','ZED Park — 65 of the project’s 165 acres','حديقة زيد — ٦٥ من أصل ١٦٥ فداناً','am_centralpark',128),
  ('zw_parking','Underground parking, concierge & lifts','جراج تحت الأرض وكونسيرج ومصاعد','am_parking',129),
  ('zw_sports','Sports complex — DBB soccer, BTT Barcelona tennis & paddle','مجمّع رياضي — كرة قدم مع DBB، وتنس وبادل مع BTT برشلونة','am_sports',130)
) as v(token, name_en, name_ar, icon, sort_order)
on conflict (token) do update set name_en = excluded.name_en,
  name_ar = excluded.name_ar, icon = excluded.icon;
