-- Every project is `published`: they are all live on the site today, and a
-- migration must not quietly unpublish anything. The array columns carry an
-- explicit ::text[] because a literal in a VALUES list is otherwise plain text.
insert into cms.projects (slug, name_en, name_ar, developer_id, location_id, stage,
  description_en, description_ar, price_from, down_payment_pct, instalment_years,
  delivery_label, finishing_en, finishing_ar, unit_types_en, unit_types_ar,
  tags_en, tags_ar, status, published_at)
select v.slug, v.name_en, v.name_ar, dev.id, loc.id, v.stage::cms.project_stage,
  v.description_en, v.description_ar, v.price_from::bigint, v.dp::numeric, v.years::numeric,
  v.delivery_label, v.finishing_en, v.finishing_ar, v.unit_types_en, v.unit_types_ar,
  v.tags_en::text[], v.tags_ar::text[], 'published', now()
from (values
  ('silversands-silvertown','Silversands Silvertown','سيلفر ساندز سيلفر تاون','ora','sahel','launch','Silversands Silvertown by ORA in Sidi Heneish — 7 primary unit types from the developer''s own price list: chalet, townhouse, villa. From 150 m² and EGP 27,000,000, on a 10% down payment over 10 years, handover 2030.','سيلفر ساندز سيلفر تاون من أورا في سيدي حنيش — ٧ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شاليه، تاون هاوس، فيلا. من ١٥٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',27000000,10,10,'2030',null,null,'Chalet · Townhouse · Villa','شاليه · تاون هاوس · فيلا','{"Sidi Heneish","7 units","150–250 m²"}','{"سيدي حنيش","٧ وحدات","١٥٠–٢٥٠ م²"}'),
  ('village-de-la-capitale','Village de la Capitale','فيلاج دي لا كابيتال','palmhills','capital','primary','A 290-feddan Palm Hills community with apartments, townhouses and villas, water features, sports courts and club houses. Developer-direct primary units on a 12-year plan.','مجتمع بالم هيلز على ٢٩٠ فداناً يضم شققاً وتاون هاوس وفيلات مع نوافير مائية وملاعب رياضية وكلوب هاوس. وحدات أولية من المطوّر مباشرة بتقسيط ١٢ سنة.',6400000,1.5,12,'2029','Core & shell','خرسانة على المحارة','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"New Capital","290 feddans"}','{"العاصمة الإدارية","٢٩٠ فدان"}'),
  ('palm-hills-new-cairo','Palm Hills New Cairo','بالم هيلز القاهرة الجديدة','palmhills','newcairo','primary','Palm Hills’ established 500-feddan New Cairo community — the fully finished Cleo apartments plus villas, a 40-feddan Palm Hills club, hotel and international school. Developer-direct primary units.','مجتمع بالم هيلز المتكامل على ٥٠٠ فدان بالقاهرة الجديدة — شقق Cleo كاملة التشطيب وفيلات ونادي بالم هيلز على ٤٠ فداناً وفندق ومدرسة دولية. وحدات أولية من المطوّر مباشرة.',10400000,5,8,'2027','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Villa','شقة · فيلا','{"New Cairo","500 feddans"}','{"القاهرة الجديدة","٥٠٠ فدان"}'),
  ('97-hills','97 Hills','٩٧ هيلز','palmhills','newcairo','primary','A 97-feddan Palm Hills community in New Cairo built around lagoons and a community centre, with family houses, townhouses, twin houses and villas. Developer-direct primary units over 10 years.','مجتمع بالم هيلز على ٩٧ فداناً بالقاهرة الجديدة حول البحيرات ومركز مجتمعي، ببيوت عائلية وتاون هاوس وتوين هاوس وفيلات. وحدات أولية من المطوّر مباشرة بتقسيط ١٠ سنوات.',25800000,5,10,'2029','Core & shell / fully finished','خرسانة / تشطيب كامل','Townhouse · Twin house · Villa','تاون هاوس · توين هاوس · فيلا','{"New Cairo","Lagoons"}','{"القاهرة الجديدة","بحيرات"}'),
  ('palmet-new-cairo','Palmet New Cairo','بالمت القاهرة الجديدة','palmhills','newcairo','primary','A 100-feddan Palm Hills commercial destination in New Cairo on Palm Hills Drive — retail, offices, banks, clinics and pharmacies. Developer-direct primary units.','وجهة بالم هيلز التجارية على ١٠٠ فدان بالقاهرة الجديدة على Palm Hills Drive — محلات ومكاتب وبنوك وعيادات وصيدليات. وحدات أولية من المطوّر مباشرة.',13000000,5,8,'2027','Core & shell','خرسانة على المحارة','Retail · Offices · Clinics','محلات · مكاتب · عيادات','{"New Cairo","Commercial"}','{"القاهرة الجديدة","تجاري"}'),
  ('px-new-cairo','PX','بي إكس','palmhills','newcairo','primary','PX is Palm Hills’ 370-feddan New Cairo district — G+3 apartments, townhouses and villas with a Palm Hills club and commercial hub. Developer-direct primary units, delivery 2030.','PX هو حي بالم هيلز على ٣٧٠ فداناً بالقاهرة الجديدة — شقق أرضي+٣ وتاون هاوس وفيلات مع نادي بالم هيلز ومنطقة تجارية. وحدات أولية من المطوّر مباشرة، التسليم ٢٠٣٠.',13500000,5,8,'2030','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"New Cairo","370 feddans"}','{"القاهرة الجديدة","٣٧٠ فدان"}'),
  ('jirian-zayed','Palm Hills Jirian','بالم هيلز جيريان','palmhills','zayed','primary','A 360-feddan Palm Hills community in West Cairo with Nile views — fully finished apartments, townhouses and villas, hotels and a commercial spine. Developer-direct primary units.','مجتمع بالم هيلز على ٣٦٠ فداناً بغرب القاهرة بإطلالات على النيل — شقق وتاون هاوس وفيلات كاملة التشطيب وفنادق ومحور تجاري. وحدات أولية من المطوّر مباشرة.',7800000,5,8,'2029','Fully finished','تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"Sheikh Zayed","Nile views"}','{"الشيخ زايد","إطلالة على النيل"}'),
  ('hacienda-blue','Hacienda Blue','هاسيندا بلو','palmhills','raselhekma','primary','Palm Hills’ 118-acre beachfront resort at Ras El Hekma (Km 166) with lagoons, parks and a 400m beach — G+1 apartments, cabins, townhouses and water villas. Developer-direct primary units.','منتجع بالم هيلز الشاطئي على ١١٨ فداناً برأس الحكمة (كيلو ١٦٦) ببحيرات وحدائق وشاطئ ٤٠٠ متر — شقق أرضي+١ وكبائن وتاون هاوس وفيلات مائية. وحدات أولية من المطوّر مباشرة.',19600000,2.5,12,'2030','Fully finished (no kitchen/AC)','تشطيب كامل (بدون مطبخ وتكييف)','Apartment · Cabin · Townhouse · Villa','شقة · كابين · تاون هاوس · فيلا','{"Ras El Hekma","400m beachfront"}','{"رأس الحكمة","واجهة بحرية ٤٠٠م"}'),
  ('hacienda-waters','Hacienda Waters','هاسيندا ووترز','palmhills','raselhekma','primary','A 161-acre Palm Hills beachfront community at Ras El Hekma (Km 191) with lagoons, an aqua park and a 400m beach — chalets, cabins and water villas. Developer-direct primary units.','مجتمع بالم هيلز الشاطئي على ١٦١ فداناً برأس الحكمة (كيلو ١٩١) ببحيرات وأكوا بارك وشاطئ ٤٠٠ متر — شاليهات وكبائن وفيلات مائية. وحدات أولية من المطوّر مباشرة.',14100000,2.5,12,'2029','Fully finished (no kitchen/AC)','تشطيب كامل (بدون مطبخ وتكييف)','Chalet · Cabin · Villa','شاليه · كابين · فيلا','{"Ras El Hekma","Aqua park"}','{"رأس الحكمة","أكوا بارك"}'),
  ('hacienda-heneish','Hacienda Heneish','هاسيندا حنيش','palmhills','raselhekma','primary','A 420-feddan Palm Hills resort on the North Coast with a Marriott hotel, strip mall and 1.1km of beachfront — G+3 apartments, chalets, townhouses and standalone villas. Developer-direct primary units.','منتجع بالم هيلز على ٤٢٠ فداناً بالساحل الشمالي بفندق ماريوت وممشى تجاري وواجهة بحرية ١٫١ كم — شقق أرضي+٣ وشاليهات وتاون هاوس وفيلات مستقلة. وحدات أولية من المطوّر مباشرة.',16000000,5,8,'2029','Fully finished','تشطيب كامل','Apartment · Chalet · Townhouse · Villa','شقة · شاليه · تاون هاوس · فيلا','{"Ras El Hekma","Marriott hotel"}','{"رأس الحكمة","فندق ماريوت"}'),
  ('hacienda-west','Hacienda West','هاسيندا ويست','palmhills','raselhekma','primary','A 132-feddan Palm Hills beach community at Ras El Hekma (Km 208) with a hotel, clubhouse, lagoons and a 400m beach — chalets, cabins and villas. Developer-direct primary units.','مجتمع بالم هيلز الشاطئي على ١٣٢ فداناً برأس الحكمة (كيلو ٢٠٨) بفندق وكلوب هاوس وبحيرات وشاطئ ٤٠٠ متر — شاليهات وكبائن وفيلات. وحدات أولية من المطوّر مباشرة.',23800000,10,7,'2027','Fully finished / core & shell','تشطيب كامل / خرسانة','Chalet · Cabin · Villa','شاليه · كابين · فيلا','{"Ras El Hekma","Beachfront"}','{"رأس الحكمة","واجهة بحرية"}')
) as v(slug, name_en, name_ar, dev_slug, area_slug, stage, description_en, description_ar,
       price_from, dp, years, delivery_label, finishing_en, finishing_ar,
       unit_types_en, unit_types_ar, tags_en, tags_ar)
join cms.developers dev on dev.slug = v.dev_slug
join cms.locations  loc on loc.slug = v.area_slug
on conflict (slug) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar,
  developer_id = excluded.developer_id, location_id = excluded.location_id,
  stage = excluded.stage, description_en = excluded.description_en,
  description_ar = excluded.description_ar, price_from = excluded.price_from,
  down_payment_pct = excluded.down_payment_pct, instalment_years = excluded.instalment_years,
  delivery_label = excluded.delivery_label, finishing_en = excluded.finishing_en,
  finishing_ar = excluded.finishing_ar, unit_types_en = excluded.unit_types_en,
  unit_types_ar = excluded.unit_types_ar, tags_en = excluded.tags_en, tags_ar = excluded.tags_ar;
