-- Every project is `published`: they are all live on the site today, and a
-- migration must not quietly unpublish anything. The array columns carry an
-- explicit ::text[] because a literal in a VALUES list is otherwise plain text.
insert into cms.projects (slug, name_en, name_ar, developer_id, location_id, stage,
  description_en, description_ar, price_from, down_payment_pct, instalment_years,
  delivery_label, finishing_en, finishing_ar, unit_types_en, unit_types_ar,
  tags_en, tags_ar, status, published_at)
select v.slug, v.name_en, v.name_ar, dev.id, loc.id, v.stage::cms.project_stage,
  v.description_en, v.description_ar, v.price_from::bigint, v.dp::numeric, v.years::numeric,
  v.delivery_label, v.finishing_en, v.finishing_ar, v.unit_types_en, v.unit_types_ar,
  v.tags_en::text[], v.tags_ar::text[], 'published', now()
from (values
  ('fifth-square','Fifth Square','فيفث سكوير','marasem','fifthsettlement','primary','A prime Fifth Settlement community with developer-direct primary units and long plans.','مجتمع مميّز بالتجمع الخامس مع وحدات أولية من المطوّر مباشرة وخطط طويلة.',6200000,10,8,'2027','Semi-finished','نصف تشطيب','Apartment · Duplex · Villa','شقة · دوبلكس · فيلا','{"Fifth Settlement","Prime"}','{"التجمع الخامس","موقع مميّز"}'),
  ('cairo-gate','Cairo Gate','كايرو جيت','emaarmisr','zayed','launch','A gateway West Cairo launch by Emaar Misr on the Cairo–Alexandria corridor.','إطلاق مميّز بغرب القاهرة من إعمار مصر على محور القاهرة–الإسكندرية.',11500000,10,8,'2027','Semi-finished','نصف تشطيب','Apartment · Townhouse','شقة · تاون هاوس','{"Sheikh Zayed","Gateway"}','{"الشيخ زايد","بوابة"}'),
  ('aeon','Aeon','إيون','marakez','october','launch','A mixed-use launch in 6th of October pairing homes with retail and offices.','إطلاق متعدد الاستخدامات ب٦ أكتوبر يجمع السكن مع التجزئة والمكاتب.',36000000,10,4,'2026','Semi-finished','نصف تشطيب','Apartment','شقة','{"6th of October","Mixed-use"}','{"٦ أكتوبر","متعدد الاستخدامات"}'),
  ('il-monte-galala','Il Monte Galala','إل مونتي جلالة','tatweer','sokhna','primary','A terraced mountain-and-sea resort in Ain Sokhna by Tatweer Misr.','منتجع جبلي بحري متدرّج بالعين السخنة من تطوير مصر.',7400000,5,10,'2029','Fully finished','تشطيب كامل','Standalone Villa · Studio · Apartment · Chalet · Loft · Twin House · Cabin · Penthouse','فيلا مستقلة · استوديو · شقة · شاليه · لوفت · توين هاوس · كابين · بنتهاوس','{"Ain Sokhna","Sea view"}','{"العين السخنة","إطلالة بحر"}'),
  ('ogami-north-coast','Ogami','أوجامي','sodic','raselhekma','launch','SODIC’s Japanese-inspired Ras El Hekma resort at Km 205 on 440 feddan — an 800m private crystalline beach, 11km of crystal lagoons (120,000 m² swimmable) and a Nobu hotel with branded residences. Its walkable Botanica Town phase adds G+2 residences with private ground-floor gardens and maid’s rooms, fully finished with built-in AC. Developer-direct primary units from 5% down over up to 8 years.','منتجع سوديك المستوحى من اليابان برأس الحكمة عند الكيلو ٢٠٥ على مساحة ٤٤٠ فدان — شاطئ كريستالي خاص ٨٠٠ متر و١١ كم بحيرات كريستالية (١٢٠٬٠٠٠ م² قابلة للسباحة) وفندق Nobu بريزيدنسز فندقية. وتضيف مرحلة Botanica Town المخصّصة للمشاة وحدات أرضي+طابقين بحدائق خاصة بالأرضي وغرفة خادمة، كاملة التشطيب بتكييف مدمج. وحدات أولية من المطوّر مباشرة من مقدم ٥٪ وتقسيط حتى ٨ سنوات.',22329000,5,8,'2029–2030','Fully finished','تشطيب كامل','Apartment · Chalet · Townhouse · Twin house · Villa','شقة · شاليه · تاون هاوس · توين هاوس · فيلا','{"Ras El Hekma","Nobu-branded","5% down"}','{"رأس الحكمة","بشراكة Nobu","مقدم ٥٪"}'),
  ('ramla-ras-el-hekma','Ramla','رملة','marakez','raselhekma','launch','Marakez’s Ramla at Kilo 215, Ras El Hekma — a 402-acre beachfront community (WATG master plan) with a 1.4km beach, a 22-acre lagoon and a 13-acre sports campus, laid out across the Breeze, Acacia, Oasis, The Town and Dunes neighbourhoods. Fully finished chalets, duplexes, a penthouse, townhouses, twin houses and villas with concealed AC, plus collaborations with Adrère Amellal, Azza Fahmy and Mariolino. From 10% down over up to 7 years; handover between 2027 and 2030. Developer-direct primary units.','وجهة رملة من مراكز عند الكيلو ٢١٥ برأس الحكمة — مجتمع شاطئي على ٤٠٢ فدان (تخطيط WATG) بشاطئ ١٫٤ كم وبحيرة ٢٢ فداناً وكامباس رياضي ١٣ فداناً، موزّع على أحياء بريز وأكاسيا وأواسيس وذا تاون وديونز. شاليهات ودوبلكس وبنتهاوس وتاون هاوس وتوين هاوس وفيلات كاملة التشطيب بتكييف مخفي، بالتعاون مع Adrère Amellal وعزة فهمي وMariolino. من مقدم ١٠٪ وتقسيط حتى ٧ سنوات؛ التسليم بين ٢٠٢٧ و٢٠٣٠. وحدات أولية من المطوّر مباشرة.',23418000,10,7,'2027','Fully finished','تشطيب كامل','Chalet · Duplex · Penthouse · Townhouse · Twin house · Villa','شاليه · دوبلكس · بنتهاوس · تاون هاوس · توين هاوس · فيلا','{"Ras El Hekma","1.4km beach","5% down"}','{"رأس الحكمة","شاطئ ١٫٤ كم","مقدم ٥٪"}'),
  ('caesar-north-coast','Caesar','قيصر','sodic','raselhekma','launch','SODIC’s Caesar on the North Coast — a terraced bay with 1.2km of pristine beachfront and 20,000+ sqm of swimmable crystal lagoons, a clubhouse, the Matcha retail village and a beachfront pier. Fully finished townhomes, twin homes, urban and standalone villas. Developer-direct primary units, from 5% down over 8 years.','مشروع قيصر من سوديك على الساحل الشمالي — خليج متدرّج بشاطئ نقي ١٫٢ كم وأكثر من ٢٠٬٠٠٠ م² بحيرات كريستالية للسباحة، وكلوب هاوس وقرية Matcha التجارية وبروميناد على الشاطئ. تاون هاوس وتوين هاوس وفيلات حضرية ومستقلة كاملة التشطيب. وحدات أولية من المطوّر مباشرة، من مقدم ٥٪ وتقسيط ٨ سنوات.',39200000,5,8,null,'Fully finished','تشطيب كامل','Townhouse · Twin house · Villa','تاون هاوس · توين هاوس · فيلا','{"Ras El Hekma","1.2km beach","5% down"}','{"رأس الحكمة","شاطئ ١٫٢ كم","مقدم ٥٪"}'),
  ('june-north-coast','June','جون','sodic','raselhekma','launch','SODIC’s June — a Miami-inspired North Coast beach town where homes rise 50m above sea level for panoramic views, with a Marriott hotel and Lemon Spaces serviced apartments, a boardwalk, swimmable lagoons and infinity pools. Fully finished Coral and Opal villas. Developer-direct primary units, from 5% down over 8 years.','مشروع جون من سوديك — بلدة شاطئية بإلهام ميامي على الساحل الشمالي ترتفع منازلها ٥٠ متراً فوق سطح البحر لإطلالات بانورامية، بفندق ماريوت وشقق فندقية Lemon Spaces وبوردووك وبحيرات للسباحة وحمّامات إنفينيتي. فيلات Coral وOpal كاملة التشطيب. وحدات أولية من المطوّر مباشرة، من مقدم ٥٪ وتقسيط ٨ سنوات.',89300000,5,8,null,'Fully finished','تشطيب كامل','Villa','فيلا','{"Ras El Hekma","Miami-inspired","Marriott"}','{"رأس الحكمة","بإلهام ميامي","ماريوت"}'),
  ('badya-october','Badya','بادية','palmhills','october','launch','Palm Hills’ large master-planned city in West Cairo, organised into walkable districts with schools, parks and retail. Developer-direct primary units.','مدينة بالم هيلز المتكاملة الكبرى بغرب القاهرة، مقسّمة إلى أحياء صديقة للمشاة بمدارس وحدائق ومحال. وحدات أولية من المطوّر مباشرة.',5600000,10,8,'2029','Fully finished / core & shell','تشطيب كامل / خرسانة','Apartment · Townhouse · Twin house · Villa','شقة · تاون هاوس · توين هاوس · فيلا','{"6th of October","Master-planned city"}','{"٦ أكتوبر","مدينة متكاملة"}'),
  ('the-estates-zayed','The Estates','ذي إستيتس','sodic','zayed','primary','A SODIC community in New Zayed, west of Cairo — low-density residences set among landscaped open space. Developer-direct primary units.','مجتمع من سوديك بزايد الجديدة غرب القاهرة — وحدات بكثافة منخفضة وسط مساحات خضراء منسّقة. وحدات أولية من المطوّر مباشرة.',12000000,10,7,'2027','Semi-finished','نصف تشطيب','Apartment · Villa','شقة · فيلا','{"New Zayed","Low-density"}','{"زايد الجديدة","كثافة منخفضة"}'),
  ('aliva-mostakbal','Aliva','أليفا','mountainview','mostakbal','launch','A Mountain View community in Mostakbal City built around the developer’s signature parks and lifestyle master plan. Developer-direct primary units.','مجتمع من ماونتن ڤيو بمدينة المستقبل مبني حول مخطط الحدائق واللايف ستايل المميّز للمطوّر. وحدات أولية من المطوّر مباشرة.',6000000,5,9,'2029','Semi-finished','نصف تشطيب','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"Mostakbal City","Parks & lifestyle"}','{"مدينة المستقبل","حدائق ولايف ستايل"}'),
  ('mountain-view-11','Mountain View 1.1','ماونتن ڤيو ١٫١','mountainview','newcairo','primary','A Mountain View development in East Cairo, launched in 2022 and building in two phases the company kit names The Villas and The Park.','مشروع من ماونتن ڤيو بشرق القاهرة، أُطلق عام ٢٠٢٢ ويُبنى على مرحلتين يسمّيهما كتيّب الشركة «ذا فيلاز» و«ذا بارك».',null,null,null,null,null,null,null,null,'{"New Cairo","Launched 2022"}','{"القاهرة الجديدة","أُطلق ٢٠٢٢"}'),
  ('grand-valleys','Grand Valleys','جراند فالييز','mountainview','newcairo','primary','Mountain View’s East Cairo launch of 2025, already photographed under construction in the company kit.','إطلاق ماونتن ڤيو بشرق القاهرة لعام ٢٠٢٥، ويظهر في كتيّب الشركة قيد الإنشاء بالفعل.',null,null,null,null,null,null,null,null,'{"New Cairo","Launched 2025"}','{"القاهرة الجديدة","أُطلق ٢٠٢٥"}'),
  ('icity-october','Mountain View iCity October','ماونتن ڤيو آي سيتي أكتوبر','mountainview','october','primary','The West Cairo iCity, launched in 2017. Club park Phase 1 and MV Park are handed over, while Mountain Park, Lagoon Beach Park and Club park Phase 2 have been building since 2022.','آي سيتي غرب القاهرة، أُطلقت عام ٢٠١٧. سُلّمت «كلوب بارك المرحلة ١» و«إم ڤي بارك»، بينما يجري بناء «ماونتن بارك» و«لاجون بيتش بارك» و«كلوب بارك المرحلة ٢» منذ ٢٠٢٢.',null,null,null,null,null,null,null,null,'{"6th of October","Launched 2017"}','{"٦ أكتوبر","أُطلق ٢٠١٧"}'),
  ('kingsway-october','Kingsway','كينجزواي','mountainview','october','primary','Launched in 2024 under the Mountain View Signature line, and on site in West Cairo since.','أُطلق عام ٢٠٢٤ ضمن خط «ماونتن ڤيو سيجنتشر»، والعمل جارٍ في موقعه بغرب القاهرة منذ ذلك الحين.',null,null,null,null,null,null,null,null,'{"6th of October","Mountain View Signature"}','{"٦ أكتوبر","ماونتن ڤيو سيجنتشر"}'),
  ('jirian','Jirian','جيريان','mountainview','october','primary','A 2025 launch in West Cairo, developed by Mountain View together with Nations of Sky and drawn along the water.','إطلاق ٢٠٢٥ في غرب القاهرة، تطوّره ماونتن ڤيو بالشراكة مع «نيشنز أوف سكاي»، ومرسوم على امتداد الماء.',null,null,null,null,null,null,null,null,'{"West Cairo","With Nations of Sky"}','{"غرب القاهرة","بالشراكة مع نيشنز أوف سكاي"}'),
  ('lvls-north-coast','LVLS','لِفلز','mountainview','sahel','primary','Mountain View’s North Coast development, launched in 2023 and under construction on the shore.','مشروع ماونتن ڤيو على الساحل الشمالي، أُطلق عام ٢٠٢٣ وتحت الإنشاء على الشاطئ.',null,null,null,null,null,null,null,null,'{"North Coast","Launched 2023"}','{"الساحل الشمالي","أُطلق ٢٠٢٣"}'),
  ('plage-north-coast','plage','بلاج','mountainview','sahel','primary','A 2024 Mountain View launch on the North Coast.','إطلاق من ماونتن ڤيو على الساحل الشمالي عام ٢٠٢٤.',null,null,null,null,null,null,null,null,'{"North Coast","Launched 2024"}','{"الساحل الشمالي","أُطلق ٢٠٢٤"}'),
  ('crysta-north-coast','Crysta','كريستا','mountainview','sahel','primary','Mountain View’s newest coastal launch, dated 2025 in the company kit.','أحدث إطلاق ساحلي من ماونتن ڤيو، ومؤرَّخ بعام ٢٠٢٥ في كتيّب الشركة.',null,null,null,null,null,null,null,null,'{"North Coast","Launched 2025"}','{"الساحل الشمالي","أُطلق ٢٠٢٥"}'),
  ('fouka-bay','Fouka Bay','فوكا باي','tatweer','sahel','primary','Tatweer Misr’s North Coast resort near Ras El Hekma, known for terraced beachfront and turquoise swimmable lagoons. Developer-direct primary units.','منتجع تطوير مصر على الساحل الشمالي قرب رأس الحكمة، معروف بالشاطئ المتدرّج والبحيرات الفيروزية للسباحة. وحدات أولية من المطوّر مباشرة.',13900000,5,9,'2030','Fully finished','تشطيب كامل','Chalet · Apartment','شاليه · شقة','{"North Coast","Turquoise lagoons"}','{"الساحل الشمالي","بحيرات فيروزية"}'),
  ('vinci-capital','Vinci','فينشي','misritalia','capital','primary','Misr Italia’s green, technology-enabled community in the New Administrative Capital, with generous landscaping and amenities. Developer-direct primary units.','مجتمع مصر إيطاليا الأخضر المزوّد بالتقنيات بالعاصمة الإدارية الجديدة، بمساحات خضراء ومرافق واسعة. وحدات أولية من المطوّر مباشرة.',6500000,10,8,'2028','Semi-finished','نصف تشطيب','Apartment · Villa','شقة · فيلا','{"New Capital","Green living"}','{"العاصمة الإدارية","معيشة خضراء"}'),
  ('masyaf-ras-alhekma','Masyaf Ras Alhekma','مصياف رأس الحكمة','msquared','raselhekma','primary','Inspired by Greek architecture, where floating seascapes and natural simplicity live indoors, Masyaf Ras Alhekma stretches over 112 feddans of land lapping a pristine 730-metre beachfront on the Mediterranean shore. Master planned by M squared, it lifts its homes onto elevated platforms so every owner gets an equal view. Its own downtown carries Ritsa, the Barten restaurant, the Peppermint wellbeing centre and the Marmarica boutique cabanas.','مستوحى من العمارة اليونانية حيث تعيش المشاهد البحرية والبساطة الطبيعية في الداخل، يمتد مصياف رأس الحكمة على ١١٢ فداناً بواجهة بحرية بكر بطول ٧٣٠ متراً على شاطئ المتوسط. وضعت إم سكويرد مخططه العام ورفعت منازله على منصات متدرّجة ليحصل كل مالك على إطلالة متساوية. ويضم داون تاون خاصاً به يحوي «ريتسا» ومطعم «بارتن» ومركز «بيبرمنت» للعافية وكابانات «مرماريكا» البوتيكية.',12190419,10,10,'2028–2030',null,null,'Chalet · Duplex · Penthouse · Townhouse · Villa','شاليه · دوبلكس · بنتهاوس · تاون هاوس · فيلا','{"Ras Al Hekma","112 feddans","730 m beachfront"}','{"رأس الحكمة","١١٢ فدان","٧٣٠ م واجهة بحرية"}'),
  ('trio-new-cairo','TRIO','تريو','msquared','newcairo','primary','A signature boutique community on 35.5 acres of verdant land at the heart of New Cairo. TRIO is characterised by a “three villas per complex” concept with hanging gardens and flying pools, and each duplex has its own garden and maximum privacy. Three phases sit around a central spine carrying a reading work station, a yoga garden, a meditation zone and a kids’ play zone.','مجتمع بوتيكي مميّز على ٣٥٫٥ فدان من الأرض الخضراء في قلب القاهرة الجديدة. يتميّز «تريو» بمفهوم «ثلاث فيلات لكل مجمّع» بحدائق معلّقة وحمامات سباحة طائرة، ولكل دوبلكس حديقته الخاصة وأقصى درجات الخصوصية. وتلتفّ ثلاث مراحل حول محور مركزي يضم ركن قراءة وعمل، وحديقة يوجا، ومنطقة تأمّل، ومنطقة لعب للأطفال.',11637891,10,10,'2027–2028',null,null,'Apartment · Duplex · Townhouse · Penthouse','شقة · دوبلكس · تاون هاوس · بنتهاوس','{"New Cairo","35.5 acres","Three villas per complex"}','{"القاهرة الجديدة","٣٥٫٥ فدان","ثلاث فيلات لكل مجمّع"}'),
  ('mist-new-cairo','MIST','ميست','msquared','newcairo','launch','In East Cairo’s Golden Square, MIST rises as a new-generation mixed-use development spanning 45 feddans, with over 18,000 square metres of lakes and water paths flowing through the land and more than 80 per cent of the residential space kept green. MIST is not a place you escape to. It is a place you live within, pass through, and engage with fully — a passage, a lifestyle artery and a destination all at once. Rather than rigid zones, the community unfolds in intuitive layers: serene homes flow alongside water and greenery, while a commercial promenade brings daily vibrance, and a public plaza at the centre ties it together. The name was chosen for its relevance to motion, transformation and fluidity.','في جولدن سكوير بشرق القاهرة يقوم «ميست» كمشروع متعدد الاستخدامات من جيل جديد على ٤٥ فداناً، بأكثر من ١٨٬٠٠٠ متر مربع من البحيرات والممرات المائية تجري في أرضه، وأكثر من ٨٠٪ من المساحة السكنية مُبقاة خضراء. و«ميست» ليس مكاناً تهرب إليه، بل مكان تعيش داخله وتمرّ به وتنخرط فيه بالكامل — ممرّ وشريان لايف ستايل ووجهة في آن. وبدلاً من المناطق الجامدة، ينكشف المجتمع في طبقات بديهية: منازل هادئة تنساب بمحاذاة الماء والخضرة، وبروميناد تجاري يمنح الحياة اليومية حيويتها، وبلازا عامة في المركز تربط كل شيء. واختير الاسم لصلته بالحركة والتحوّل والانسيابية.',17602921,5,10,'2030',null,null,'Apartment · Penthouse · Townhouse','شقة · بنتهاوس · تاون هاوس','{"East Cairo Golden Square","45 feddans","18,000 m² of lakes"}','{"جولدن سكوير شرق القاهرة","٤٥ فدان","١٨٬٠٠٠ م² بحيرات"}'),
  ('31-west-october','31 WEST','٣١ ويست','msquared','october','primary','31 WEST epitomises refined living within 31 acres at one of the most exclusive locations in 6th of October, where every detail is curated to exude exclusivity and sophistication. From grand water features and inspiring designs to landscaped surroundings and the first-of-its-kind Senior Executive Suites, the project stands as a testament to timeless elegance and elite living.','يجسّد «٣١ ويست» السكن الراقي على ٣١ فداناً في أحد أكثر مواقع ٦ أكتوبر تميّزاً، حيث كل تفصيلة منتقاة لتفيض تفرّداً ورقيّاً. ومن المسطحات المائية الكبرى والتصاميم الملهمة إلى المحيط المنسّق والأجنحة التنفيذية الأولى من نوعها، يقف المشروع شاهداً على الأناقة الخالدة والحياة الصفوية.',13237120,5,10,'2030','Apartments fully finished · single homes semi-finished','الشقق كاملة التشطيب · المنازل المستقلة نصف تشطيب','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"6th of October","31 acres","570 units"}','{"٦ أكتوبر","٣١ فدان","٥٧٠ وحدة"}'),
  ('41-business-district','41 Business District','٤١ بيزنس ديستريكت','msquared','newcairo','primary','A commercial landmark at the heart of the Kattameya Ring Road, connecting multiple districts of the city. 41 Business District is an innovative, multipurpose concept that blends cutting-edge office and clinic spaces with commercial luxuries in one building — a bank, café, restaurant, gym, furniture, barber, sports, jewellery and market at street level.','معلم تجاري في قلب الطريق الدائري بالقطامية، يربط عدة أحياء بالمدينة. «٤١ بيزنس ديستريكت» مفهوم مبتكر متعدد الاستخدامات يمزج مساحات المكاتب والعيادات الحديثة مع رفاهيات تجارية في مبنى واحد — بنك ومقهى ومطعم وجيم وأثاث وحلاق ورياضة ومجوهرات وسوق على مستوى الشارع.',13962832,10,8,'2029',null,null,'Office','مكتب','{"Kattameya Ring Road","Commercial landmark"}','{"الطريق الدائري القطامية","معلم تجاري"}'),
  ('zed-east','ZED East','زيد إيست','ora','newcairo','launch','ZED East by ORA in New Cairo — 8 primary unit types from the developer''s own price list: apartment, loft, studio. From 65 m² and EGP 8,900,000, on a 10% down payment over 10 years, handover 2027–2030.','زيد إيست من أورا في القاهرة الجديدة — ٨ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شقة، لوفت، استوديو. من ٦٥ م² و٨٬٩٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٢٧–٢٠٣٠.',8900000,10,10,'2027–2030',null,null,'Apartment · Loft · Studio','شقة · لوفت · استوديو','{"New Cairo","8 units","65–300 m²"}','{"القاهرة الجديدة","٨ وحدات","٦٥–٣٠٠ م²"}'),
  ('zed-east-emerald','ZED East Emerald','زيد إيست إميرالد','ora','newcairo','launch','ZED East Emerald by ORA in New Cairo — 6 primary unit types from the developer''s own price list: duplex, fourplex, townhouse, standalone villa. From 174 m² and EGP 27,000,000, on a 10% down payment over 10 years, handover 2030.','زيد إيست إميرالد من أورا في القاهرة الجديدة — ٦ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: دوبلكس، فوربلكس، تاون هاوس، فيلا مستقلة. من ١٧٤ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',27000000,10,10,'2030',null,null,'Duplex · Fourplex · Townhouse · Standalone Villa','دوبلكس · فوربلكس · تاون هاوس · فيلا مستقلة','{"New Cairo","6 units","174–290 m²"}','{"القاهرة الجديدة","٦ وحدات","١٧٤–٢٩٠ م²"}'),
  ('zed-west','ZED West','زيد ويست','ora','zayed','launch','ZED West by ORA in New Zayed — 7 primary unit types from the developer''s own price list: studio, apartment. From 60 m² and EGP 9,000,000, on a 10% down payment over 10 years, handover 2030.','زيد ويست من أورا في زايد الجديدة — ٧ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: استوديو، شقة. من ٦٠ م² و٩٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',9000000,10,10,'2030',null,null,'Studio · Apartment','استوديو · شقة','{"New Zayed","7 units","60–219 m²"}','{"زايد الجديدة","٧ وحدات","٦٠–٢١٩ م²"}'),
  ('solana-west','Solana West','سولانا ويست','ora','zayed','launch','Solana West by ORA in New Zayed — 16 primary unit types from the developer''s own price list: villa, townhouse, twin house, apartment, loft, duplex, penthouse. From 126 m² and EGP 15,800,000, on a 10% down payment over 10 years, handover 2030.','سولانا ويست من أورا في زايد الجديدة — ١٦ نوع وحدة أولية من قائمة أسعار المطوّر نفسه: فيلا، تاون هاوس، توين هاوس، شقة، لوفت، دوبلكس، بنتهاوس. من ١٢٦ م² و١٥٬٨٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',15800000,10,10,'2030',null,null,'Villa · Townhouse · Twin House · Apartment · Loft · Duplex · Penthouse','فيلا · تاون هاوس · توين هاوس · شقة · لوفت · دوبلكس · بنتهاوس','{"New Zayed","16 units","126–337 m²"}','{"زايد الجديدة","١٦ وحدة","١٢٦–٣٣٧ م²"}'),
  ('solana-east','Solana East','سولانا إيست','ora','newcairo','launch','Solana East by ORA in New Cairo — 5 primary unit types from the developer''s own price list: apartment, twin house, villa. From 99 m² and EGP 13,900,000, on a 10% down payment over 8 years, handover 2030.','سولانا إيست من أورا في القاهرة الجديدة — ٥ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شقة، توين هاوس، فيلا. من ٩٩ م² و١٣٬٩٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ٨ سنوات، والتسليم ٢٠٣٠.',13900000,10,8,'2030',null,null,'Apartment · Twin House · Villa','شقة · توين هاوس · فيلا','{"New Cairo","5 units","99–369 m²"}','{"القاهرة الجديدة","٥ وحدات","٩٩–٣٦٩ م²"}'),
  ('silversands-crystalline','Silversands Crystalline','سيلفر ساندز كريستالين','ora','sahel','launch','Silversands Crystalline by ORA in Sidi Heneish — 9 primary unit types from the developer''s own price list: duplex, chalet, twin house, villa. From 160 m² and EGP 27,000,000, on a 15% down payment over 8 years, handover 2030.','سيلفر ساندز كريستالين من أورا في سيدي حنيش — ٩ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: دوبلكس، شاليه، توين هاوس، فيلا. من ١٦٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٥٪ على ٨ سنوات، والتسليم ٢٠٣٠.',27000000,15,8,'2030',null,null,'Duplex · Chalet · Twin House · Villa','دوبلكس · شاليه · توين هاوس · فيلا','{"Sidi Heneish","9 units","160–380 m²"}','{"سيدي حنيش","٩ وحدات","١٦٠–٣٨٠ م²"}')
) as v(slug, name_en, name_ar, dev_slug, area_slug, stage, description_en, description_ar,
       price_from, dp, years, delivery_label, finishing_en, finishing_ar,
       unit_types_en, unit_types_ar, tags_en, tags_ar)
join cms.developers dev on dev.slug = v.dev_slug
join cms.locations  loc on loc.slug = v.area_slug
on conflict (slug) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar,
  developer_id = excluded.developer_id, location_id = excluded.location_id,
  stage = excluded.stage, description_en = excluded.description_en,
  description_ar = excluded.description_ar, price_from = excluded.price_from,
  down_payment_pct = excluded.down_payment_pct, instalment_years = excluded.instalment_years,
  delivery_label = excluded.delivery_label, finishing_en = excluded.finishing_en,
  finishing_ar = excluded.finishing_ar, unit_types_en = excluded.unit_types_en,
  unit_types_ar = excluded.unit_types_ar, tags_en = excluded.tags_en, tags_ar = excluded.tags_ar;
