-- Every project is `published`: they are all live on the site today, and a
-- migration must not quietly unpublish anything. The array columns carry an
-- explicit ::text[] because a literal in a VALUES list is otherwise plain text.
insert into cms.projects (slug, name_en, name_ar, developer_id, location_id, stage,
  description_en, description_ar, price_from, down_payment_pct, instalment_years,
  delivery_label, finishing_en, finishing_ar, unit_types_en, unit_types_ar,
  tags_en, tags_ar, status, published_at)
select v.slug, v.name_en, v.name_ar, dev.id, loc.id, v.stage::cms.project_stage,
  v.description_en, v.description_ar, v.price_from::bigint, v.dp::numeric, v.years::numeric,
  v.delivery_label, v.finishing_en, v.finishing_ar, v.unit_types_en, v.unit_types_ar,
  v.tags_en::text[], v.tags_ar::text[], 'published', now()
from (values
  ('solana-east','Solana East','سولانا إيست','ora','newcairo','launch','Solana East by ORA in New Cairo — 5 primary unit types from the developer''s own price list: apartment, twin house, villa. From 99 m² and EGP 13,900,000, on a 10% down payment over 8 years, handover 2030.','سولانا إيست من أورا في القاهرة الجديدة — ٥ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شقة، توين هاوس، فيلا. من ٩٩ م² و١٣٬٩٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ٨ سنوات، والتسليم ٢٠٣٠.',13900000,10,8,'2030',null,null,'Apartment · Twin House · Villa','شقة · توين هاوس · فيلا','{"New Cairo","5 units","99–369 m²"}','{"القاهرة الجديدة","٥ وحدات","٩٩–٣٦٩ م²"}'),
  ('silversands-crystalline','Silversands Crystalline','سيلفر ساندز كريستالين','ora','sahel','launch','Silversands Crystalline by ORA in Sidi Heneish — 9 primary unit types from the developer''s own price list: duplex, chalet, twin house, villa. From 160 m² and EGP 27,000,000, on a 15% down payment over 8 years, handover 2030.','سيلفر ساندز كريستالين من أورا في سيدي حنيش — ٩ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: دوبلكس، شاليه، توين هاوس، فيلا. من ١٦٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٥٪ على ٨ سنوات، والتسليم ٢٠٣٠.',27000000,15,8,'2030',null,null,'Duplex · Chalet · Twin House · Villa','دوبلكس · شاليه · توين هاوس · فيلا','{"Sidi Heneish","9 units","160–380 m²"}','{"سيدي حنيش","٩ وحدات","١٦٠–٣٨٠ م²"}'),
  ('silversands-silvertown','Silversands Silvertown','سيلفر ساندز سيلفر تاون','ora','sahel','launch','Silversands Silvertown by ORA in Sidi Heneish — 7 primary unit types from the developer''s own price list: chalet, townhouse, villa. From 150 m² and EGP 27,000,000, on a 10% down payment over 10 years, handover 2030.','سيلفر ساندز سيلفر تاون من أورا في سيدي حنيش — ٧ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شاليه، تاون هاوس، فيلا. من ١٥٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',27000000,10,10,'2030',null,null,'Chalet · Townhouse · Villa','شاليه · تاون هاوس · فيلا','{"Sidi Heneish","7 units","150–250 m²"}','{"سيدي حنيش","٧ وحدات","١٥٠–٢٥٠ م²"}'),
  ('village-de-la-capitale','Village de la Capitale','فيلاج دي لا كابيتال','palmhills','capital','primary','A 290-feddan Palm Hills community with apartments, townhouses and villas, water features, sports courts and club houses. Developer-direct primary units on a 12-year plan.','مجتمع بالم هيلز على ٢٩٠ فداناً يضم شققاً وتاون هاوس وفيلات مع نوافير مائية وملاعب رياضية وكلوب هاوس. وحدات أولية من المطوّر مباشرة بتقسيط ١٢ سنة.',6400000,1.5,12,'2029','Core & shell','خرسانة على المحارة','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"New Capital","290 feddans"}','{"العاصمة الإدارية","٢٩٠ فدان"}'),
  ('palm-hills-new-cairo','Palm Hills New Cairo','بالم هيلز القاهرة الجديدة','palmhills','newcairo','primary','Palm Hills’ 500-feddan New Cairo community, 80% residential and facilities to 20% commercial, laid out around an interconnected park network — the Quarry Gardens, the Ridge Park, the Lifestyle Park and the Linear Parks. The brochure draws seven house types from a 296 m² twin house to a 689 m² Type A villa; the apartments are a separate building, drawn floor by floor. Developer-direct primary units, from 3% down over 10 years.','مجتمع بالم هيلز على ٥٠٠ فدان بالقاهرة الجديدة، بنسبة ٨٠٪ سكني ومرافق إلى ٢٠٪ تجاري، موزّع حول شبكة حدائق متصلة — كواري جاردنز وريدج بارك ولايف ستايل بارك والحدائق الخطية. ويرسم البروشور سبعة نماذج من توين هاوس ٢٩٦ م² إلى فيلا Type A بمساحة بناء ٦٨٩ م²؛ أما الشقق فمبنى مستقل مرسوم دوراً بدور. وحدات أولية من المطوّر مباشرة، من مقدم ٣٪ وتقسيط ١٠ سنوات.',11549000,3,10,'2030','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Twin house · Villa','شقة · توين هاوس · فيلا','{"New Cairo","500 feddans"}','{"القاهرة الجديدة","٥٠٠ فدان"}'),
  ('97-hills','97 Hills','٩٧ هيلز','palmhills','newcairo','primary','A 97-feddan Palm Hills community in New Cairo built around lagoons and a community centre, with family houses, townhouses, twin houses and villas. Developer-direct primary units over 10 years.','مجتمع بالم هيلز على ٩٧ فداناً بالقاهرة الجديدة حول البحيرات ومركز مجتمعي، ببيوت عائلية وتاون هاوس وتوين هاوس وفيلات. وحدات أولية من المطوّر مباشرة بتقسيط ١٠ سنوات.',25800000,5,10,'2029','Core & shell / fully finished','خرسانة / تشطيب كامل','Townhouse · Twin house · Villa','تاون هاوس · توين هاوس · فيلا','{"New Cairo","Lagoons"}','{"القاهرة الجديدة","بحيرات"}'),
  ('palmet-new-cairo','Palmet New Cairo','بالمت القاهرة الجديدة','palmhills','newcairo','primary','A 100-feddan Palm Hills commercial destination in New Cairo on Palm Hills Drive — retail, offices, banks, clinics and pharmacies. Developer-direct primary units.','وجهة بالم هيلز التجارية على ١٠٠ فدان بالقاهرة الجديدة على Palm Hills Drive — محلات ومكاتب وبنوك وعيادات وصيدليات. وحدات أولية من المطوّر مباشرة.',13000000,5,8,'2027','Core & shell','خرسانة على المحارة','Retail · Offices · Clinics','محلات · مكاتب · عيادات','{"New Cairo","Commercial"}','{"القاهرة الجديدة","تجاري"}'),
  ('px-new-cairo','PX','بي إكس','palmhills','october','primary','Palm Hills’ P/X — 373 feddans on the highest hill point of its West Cairo neighbourhood, master-planned by Chapman Taylor. Phase 1 is 120 feddans across eight named zones, and the brochure draws seven buildings: Villa 1 and Villa 2, Town House X, and the DUSK, DAWN, SKYE 1 and SKYE 2 apartment blocks, from a 60 m² one-bedroom to a 258 m² four-bedroom with a nanny’s room. Developer-direct primary units, from 5% down; handover 2030.','مشروع P/X من بالم هيلز — ٣٧٣ فداناً على أعلى نقطة في حيّه بغرب القاهرة، بتخطيط عام من Chapman Taylor. المرحلة الأولى ١٢٠ فداناً في ثماني مناطق مسمّاة، ويرسم البروشور سبعة مبانٍ: فيلا ١ وفيلا ٢، وتاون هاوس X، وعمارات DUSK وDAWN وSKYE 1 وSKYE 2، من شقة بغرفة ٦٠ م² إلى أربع غرف وغرفة نانية ٢٥٨ م². وحدات أولية من المطوّر مباشرة، من مقدم ٥٪؛ التسليم ٢٠٣٠.',14000000,5,10,'2030','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"6th of October","373 feddans"}','{"٦ أكتوبر","٣٧٣ فداناً"}'),
  ('jirian-zayed','Palm Hills Jirian','بالم هيلز جيريان','palmhills','zayed','primary','A 360-feddan Palm Hills community in West Cairo with Nile views — fully finished apartments, townhouses and villas, hotels and a commercial spine. Developer-direct primary units.','مجتمع بالم هيلز على ٣٦٠ فداناً بغرب القاهرة بإطلالات على النيل — شقق وتاون هاوس وفيلات كاملة التشطيب وفنادق ومحور تجاري. وحدات أولية من المطوّر مباشرة.',7800000,5,8,'2029','Fully finished','تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"Sheikh Zayed","Nile views"}','{"الشيخ زايد","إطلالة على النيل"}'),
  ('hacienda-blue','Hacienda Blue','هاسيندا بلو','palmhills','sahel','primary','Palm Hills’ boutique North Coast development, 118.5 acres with 60% given to landscape and a 24-acre freshwater lagoon winding through it. Villas, water villas, town houses, senior and junior chalets, beach cabanas and one- and two-bed cabins, with lagoons, courts, a playground, water activities, dining and a wellness centre. Developer-direct primary units, from 5% down over 12 years.','مشروع بالم هيلز البوتيك على الساحل الشمالي، ١١٨٫٥ فداناً منها ٦٠٪ مخصّصة للاندسكيب، وبحيرة عذبة ٢٤ فداناً تتخلّله. فيلات وفيلات مائية وتاون هاوس وشاليهات سينيور وجونيور وكابانات شاطئ وكابينات بغرفة وغرفتين، مع بحيرات وملاعب ومنطقة أطفال وأنشطة مائية ومطاعم ومركز عافية. وحدات أولية من المطوّر مباشرة، من مقدم ٥٪ وتقسيط ١٢ سنة.',22400000,5,12,'2031','Fully finished (no kitchen/AC)','تشطيب كامل (بدون مطبخ وتكييف)','Cabin · Chalet · Townhouse · Villa','كابين · شاليه · تاون هاوس · فيلا','{"North Coast","24-acre lagoon"}','{"الساحل الشمالي","بحيرة ٢٤ فداناً"}'),
  ('hacienda-waters','Hacienda Waters','هاسيندا ووترز','palmhills','raselhekma','primary','A 161-acre Palm Hills beachfront community at Ras El Hekma (Km 191) with lagoons, an aqua park and a 400m beach — chalets, cabins and water villas. Developer-direct primary units.','مجتمع بالم هيلز الشاطئي على ١٦١ فداناً برأس الحكمة (كيلو ١٩١) ببحيرات وأكوا بارك وشاطئ ٤٠٠ متر — شاليهات وكبائن وفيلات مائية. وحدات أولية من المطوّر مباشرة.',14100000,2.5,12,'2029','Fully finished (no kitchen/AC)','تشطيب كامل (بدون مطبخ وتكييف)','Chalet · Cabin · Villa','شاليه · كابين · فيلا','{"Ras El Hekma","Aqua park"}','{"رأس الحكمة","أكوا بارك"}'),
  ('hacienda-heneish','Hacienda Heneish','هاسيندا حنيش','palmhills','raselhekma','primary','A 420-feddan Palm Hills resort on the North Coast with a Marriott hotel, strip mall and 1.1km of beachfront — G+3 apartments, chalets, townhouses and standalone villas. Developer-direct primary units.','منتجع بالم هيلز على ٤٢٠ فداناً بالساحل الشمالي بفندق ماريوت وممشى تجاري وواجهة بحرية ١٫١ كم — شقق أرضي+٣ وشاليهات وتاون هاوس وفيلات مستقلة. وحدات أولية من المطوّر مباشرة.',16000000,5,8,'2029','Fully finished','تشطيب كامل','Apartment · Chalet · Townhouse · Villa','شقة · شاليه · تاون هاوس · فيلا','{"Ras El Hekma","Marriott hotel"}','{"رأس الحكمة","فندق ماريوت"}'),
  ('hacienda-west','Hacienda West','هاسيندا ويست','palmhills','raselhekma','primary','A 132-feddan Palm Hills beach community at Ras El Hekma (Km 208) with a hotel, clubhouse, lagoons and a 400m beach — chalets, cabins and villas. Developer-direct primary units.','مجتمع بالم هيلز الشاطئي على ١٣٢ فداناً برأس الحكمة (كيلو ٢٠٨) بفندق وكلوب هاوس وبحيرات وشاطئ ٤٠٠ متر — شاليهات وكبائن وفيلات. وحدات أولية من المطوّر مباشرة.',23800000,10,7,'2027','Fully finished / core & shell','تشطيب كامل / خرسانة','Chalet · Cabin · Villa','شاليه · كابين · فيلا','{"Ras El Hekma","Beachfront"}','{"رأس الحكمة","واجهة بحرية"}'),
  ('siyal','Siyal','سيال','orascom','redsea','primary','A neighbourhood of 78 homes inside Makadi Heights, built on 82,500 m² with only about 12% of the site covered — the rest given to open landscape, lagoons and communal ground.','حي من ٧٨ وحدة داخل مدن مكادي هايتس على ٨٢٬٥٠٠ م²، لا تشغل المباني سوى نحو ١٢٪ من الأرض — والباقي مساحات مفتوحة وبحيرات وأماكن مشتركة.',23735000,10,7,'2030','Fully finished','تشطيب كامل','Villa · Twin house · Townhouse','فيلا · توين هاوس · تاون هاوس','{"Red Sea","Makadi Bay","Lagoons"}','{"البحر الأحمر","خليج مكادي","بحيرات"}'),
  ('shams-soma','Shams Soma','شمس سوما','marakez','redsea','primary','630 homes and one hotel on 80 feddan inside Somabay, with 700 metres of coastline and two valleys running from the town down to the beach. The homes step down the natural slope of the land so the sea stays in view.','٦٣٠ وحدة وفندق واحد على ٨٠ فداناً داخل سوما باي، بواجهة بحرية طولها ٧٠٠ متر وواديين ينحدران من المدينة إلى الشاطئ. وتتدرّج الوحدات مع ميل الأرض الطبيعي ليبقى البحر في المشهد.',19500000,10,8,'2030',null,null,'Villa · Standalone villa · Townhouse · Chalet · Penthouse · Loft','فيلا · فيلا مستقلة · تاون هاوس · شاليه · بنتهاوس · لوفت','{"Red Sea","Somabay","700m coastline"}','{"البحر الأحمر","سوما باي","واجهة بحرية ٧٠٠م"}'),
  ('marassi-red-sea','Marassi Red Sea','مراسي البحر الأحمر','emaarmisr','redsea','launch','An Emaar Misr destination on the Red Sea, spanning 2,400 acres. The brochure sets out twelve luxury hotels and serviced residences, three marina experiences with 600 berths, thirty-two residential communities and 1.1 million square metres of waterbodies, alongside four beaches — the Main Beach, Island Beach, Infinity Beach and the Beach Lagoons — and a 1.5-kilometre elevated infinity beach.','وجهة من إعمار مصر على البحر الأحمر بمساحة ٢٬٤٠٠ أكر. يعرض البروشور اثني عشر فندقاً ومساكن فندقية، وثلاث تجارب مارينا بستمائة مرسى، واثنين وثلاثين مجتمعاً سكنياً، و١٫١ مليون متر مربع من المسطحات المائية، إلى جانب أربعة شواطئ — الشاطئ الرئيسي وشاطئ الجزيرة وشاطئ الإنفينيتي والبحيرات الشاطئية — وشاطئ إنفينيتي مرتفع بطول ١٫٥ كيلومتر.',28805888,5,6,'2030',null,null,'Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"Red Sea","600 berths","12 hotels"}','{"البحر الأحمر","٦٠٠ مرسى","١٢ فندقاً"}'),
  ('makadina','Makadina','مكادينا','travco','redsea','launch','A mixed-use resort destination inside Madinat Makadi on the Red Sea coast at Hurghada, with waterfront serviced homes, a clubhouse, a sports complex, a wellness hub and a shopping mall. Homeowners have access to Madinat Makadi’s 18-hole championship golf course and Makadi Water World, and to a serviced beach at Jaz Palmariva.','وجهة منتجعية متعددة الاستخدامات داخل مدينة مكادي على ساحل البحر الأحمر بالغردقة، بمنازل مخدومة على الماء وكلوب هاوس ومجمّع رياضي ومركز للعافية ومول تجاري. ولأصحاب الوحدات حق الوصول إلى ملعب الجولف البطولي ذي الثمانية عشر حفرة وحديقة مكادي المائية في مدينة مكادي، وإلى شاطئ مخدوم في فندق جاز بالماريفا.',7400000,10,8,'2030',null,null,'Apartment · Townhouse · Twin house · Villa','شقة · تاون هاوس · توين هاوس · فيلا','{"Red Sea","Madinat Makadi","18-hole golf"}','{"البحر الأحمر","مدينة مكادي","جولف ١٨ حفرة"}'),
  ('marina-gate','Marina Gate','مارينا جيت','travco','redsea','launch','The gateway phase of Almaza Bay Ras Soma on the bay of Ras Abu Soma, positioned at the marina and bridging the coast with the town. Seven products, from a one storey villa to a penthouse, each with the kit’s own floor plan; the destination around them carries a private marina, a village of dining and retail, a water sports centre and serviced homes.','المرحلة الافتتاحية من ألماظة باي رأس سوما على خليج رأس أبو سوما، تقع عند المارينا وتصل الساحل بالمدينة. سبعة منتجات من فيلا الدور الواحد إلى البنتهاوس، لكلٍّ منها مخطط أرضي في الكتيّب؛ وتضمّ الوجهة حولها مارينا خاصة وقرية للمطاعم والتجزئة ومركزاً للرياضات المائية ومنازل مخدومة.',19000000,10,8,'2030',null,null,'Duplex · Penthouse · Townhouse · Twin house · Villa','دوبلكس · بنتهاوس · تاون هاوس · توين هاوس · فيلا','{"Red Sea","Almaza Bay Ras Soma","Marina"}','{"البحر الأحمر","ألماظة باي رأس سوما","مارينا"}'),
  ('ledge-valley','Ledge Valley','ليدج فالي','orascom','redsea','primary','A waterfront neighbourhood of 274 homes on 91,049 m² inside Makadi Heights, built around expansive lagoons and landscaped open space, with a mix of one to four bedroom residences.','حي على الماء من ٢٧٤ وحدة على ٩١٬٠٤٩ م² داخل مدن مكادي هايتس، مبني حول بحيرات واسعة ومساحات مفتوحة منسّقة، بوحدات من غرفة إلى أربع غرف.',11410000,10,7,'2030',null,null,'Chalet · Penthouse','شاليه · بنتهاوس','{"Red Sea","Makadi Bay","Lagoons","Waterfront"}','{"البحر الأحمر","خليج مكادي","بحيرات","على الماء"}'),
  ('makadi-heights','Makadi Heights','مكادي هايتس','orascom','redsea','primary','Orascom Development’s town above Makadi Bay, in the heart of South Hurghada — 3.7 million m² of land, elevated 78 metres above sea level, released phase by phase from ready-to-move homes onward.','مدينة أوراسكوم للتطوير فوق خليج مكادي في قلب جنوب الغردقة — ٣٫٧ مليون م² من الأرض، على ارتفاع ٧٨ متراً فوق سطح البحر، تُطرح مرحلةً تلو الأخرى بدءاً من وحدات جاهزة للسكن.',null,10,7,'Ready – 2 years',null,null,'Apartment · Townhouse · Twin house · Villa','شقة · تاون هاوس · توين هاوس · فيلا','{"Makadi Bay","78 m above sea level"}','{"خليج مكادي","٧٨ متراً فوق سطح البحر"}'),
  ('isola-centra','ISOLA Centra','إيزولا سنترا','elmasria','newcairo','primary','El Masria’s ISOLA Centra in the heart of New Cairo, between North 90 and South 90 and a few steps from the American University in Cairo — twenty-six residential buildings of up to five levels with apartments from 87 to 260 m², around a commercial, administrative and medical spine. Developer-direct primary units.','إيزولا سنترا من المصرية جروب في قلب القاهرة الجديدة، بين التسعين الشمالي والتسعين الجنوبي وعلى بعد خطوات من الجامعة الأمريكية بالقاهرة — ستة وعشرون مبنى سكنياً حتى خمسة أدوار بشقق من ٨٧ إلى ٢٦٠ م²، حول محور تجاري وإداري وطبي. وحدات أولية من المطوّر مباشرة.',8560000,8,8,'2030',null,null,'Apartment · Loft · Administrative Office · Medical Unit · Retail','شقة · لوفت · مكتب إداري · وحدة طبية · محل تجاري','{"New Cairo","25 acres","Mixed-use"}','{"القاهرة الجديدة","٢٥ أكر","متعدد الاستخدامات"}'),
  ('isola-quattro','ISOLA Quattro','إيزولا كواترو','elmasria','newcairo','primary','El Masria’s ISOLA Quattro in New Cairo’s Golden Square, on Mohamed Ebn Zayed Road and close to the New Administrative Capital — thirteen buildings on 15 acres with only a quarter of the ground built on, and apartments from 89 to 232 m². Developer-direct primary units.','إيزولا كواترو من المصرية جروب في جولدن سكوير بالقاهرة الجديدة، على محور محمد بن زايد وقريباً من العاصمة الإدارية الجديدة — ثلاثة عشر مبنى على ١٥ أكر لا يشغل البناء منها سوى الربع، وشقق من ٨٩ إلى ٢٣٢ م². وحدات أولية من المطوّر مباشرة.',4410000,3,9,'2030',null,null,'Apartment · Loft','شقة · لوفت','{"New Cairo","Golden Square","15 acres"}','{"القاهرة الجديدة","جولدن سكوير","١٥ أكر"}'),
  ('ras-soma','Ras Soma','رأس سوما','travco','redsea','launch','Travco Properties’ Red Sea town on the bay of Ras Abu Soma, master planned by WATG — beachfront villas, quad chalets and garden apartments from 70 to 392 m², set around a marina, a town centre, two resort hotels and a green spine of parks that runs down to the sand.','مدينة ترافكو بروبرتيز على البحر الأحمر في خليج رأس أبو سوما، من تخطيط WATG — فيلات على الشاطئ وشاليهات رباعية وشقق بحدائق من ٧٠ إلى ٣٩٢ م²، حول مارينا ومركز للمدينة وفندقين منتجعيين وعمود أخضر من الحدائق ينزل حتى الرمال.',null,null,null,null,null,null,'Apartment · Chalet · Villa','شقة · شاليه · فيلا','{"Red Sea","Ras Abu Soma bay","Beachfront","Marina"}','{"البحر الأحمر","خليج رأس أبو سوما","على الشاطئ","مارينا"}')
) as v(slug, name_en, name_ar, dev_slug, area_slug, stage, description_en, description_ar,
       price_from, dp, years, delivery_label, finishing_en, finishing_ar,
       unit_types_en, unit_types_ar, tags_en, tags_ar)
join cms.developers dev on dev.slug = v.dev_slug
join cms.locations  loc on loc.slug = v.area_slug
on conflict (slug) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar,
  developer_id = excluded.developer_id, location_id = excluded.location_id,
  stage = excluded.stage, description_en = excluded.description_en,
  description_ar = excluded.description_ar, price_from = excluded.price_from,
  down_payment_pct = excluded.down_payment_pct, instalment_years = excluded.instalment_years,
  delivery_label = excluded.delivery_label, finishing_en = excluded.finishing_en,
  finishing_ar = excluded.finishing_ar, unit_types_en = excluded.unit_types_en,
  unit_types_ar = excluded.unit_types_ar, tags_en = excluded.tags_en, tags_ar = excluded.tags_ar;
