-- Where each image is attached. A link is only written when both the
-- asset and its owner exist, so a stale reference inserts nothing rather
-- than pointing at the wrong row.
insert into cms.media_links (asset_id, developer_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/logos/sodic.png','sodic','logo',0),
  ('/logos/palm-hills.png','palmhills','logo',0),
  ('/logos/mountain-view.png','mountainview','logo',0),
  ('/logos/ora.png','ora','logo',0),
  ('/logos/tatweer-misr.png','tatweer','logo',0),
  ('/logos/misr-italia.png','misritalia','logo',0),
  ('/logos/marakez.png','marakez','logo',0),
  ('/logos/lmd.png','lmd','logo',0),
  ('/logos/hyde-park.png','hydepark','logo',0),
  ('/logos/al-marasem.png','marasem','logo',0),
  ('/logos/modon.png','modon','logo',0),
  ('/logos/m-squared.png','msquared','logo',0),
  ('/logos/emaar-misr.png','emaarmisr','logo',0),
  ('/logos/orascom.png','orascom','logo',0),
  ('/logos/tmg.png','tmg','logo',0),
  ('/logos/al-ahly-sabbour.png','alahlysabbour','logo',0),
  ('/logos/hassan-allam.png','hassanallam','logo',0),
  ('/logos/il-cazar.png','ilcazar','logo',0),
  ('/logos/inertia.png','inertia','logo',0),
  ('/logos/la-vista.png','lavista','logo',0),
  ('/logos/city-edge.png','cityedge','logo',0),
  ('/logos/madinet-masr.png','madinetmasr','logo',0),
  ('/logos/qatari-diar.png','qataridiar','logo',0),
  ('/logos/saudi-egyptian.png','saudiegyptian','logo',0),
  ('/logos/sumou.png','sumou','logo',0),
  ('/logos/beit-al-bahr.png','beitalbahr','logo',0),
  ('/logos/marsa-baghush.png','baghush','logo',0),
  ('/project-media/marakez/crescent-park.webp','marakez','gallery',0),
  ('/project-media/marakez/mall-of-arabia.webp','marakez','gallery',1),
  ('/project-media/marakez/aeon-tower.webp','marakez','gallery',2),
  ('/project-media/marakez/d5-campus.webp','marakez','gallery',3),
  ('/project-media/marakez/the-park.webp','marakez','gallery',4),
  ('/project-media/sumou/st-03.webp','sumou','gallery',0),
  ('/project-media/sumou/st-01.webp','sumou','gallery',1),
  ('/project-media/sumou/ap5-0.webp','sumou','gallery',2),
  ('/project-media/sumou/st-02.webp','sumou','gallery',3),
  ('/project-media/sumou/ap2-03.webp','sumou','gallery',4),
  ('/project-media/sumou/of4.webp','sumou','gallery',5),
  ('/project-media/modon/m1.webp','modon','gallery',0),
  ('/project-media/modon/m2.webp','modon','gallery',1),
  ('/project-media/modon/m3.webp','modon','gallery',2),
  ('/project-media/modon/m4.webp','modon','gallery',3),
  ('/project-media/modon/m5.webp','modon','gallery',4),
  ('/project-media/modon/m6.webp','modon','gallery',5),
  ('/project-media/sodic/sodic-west.webp','sodic','gallery',0),
  ('/project-media/sodic/the-estates.webp','sodic','gallery',1),
  ('/project-media/sodic/eastown.webp','sodic','gallery',2),
  ('/project-media/sodic/villette.webp','sodic','gallery',3),
  ('/project-media/sodic/caesar.webp','sodic','gallery',4),
  ('/project-media/sodic/ogami.webp','sodic','gallery',5),
  ('/project-media/mountainview/park.webp','mountainview','gallery',0),
  ('/project-media/mountainview/jirian.webp','mountainview','gallery',1),
  ('/project-media/mountainview/crysta.webp','mountainview','gallery',2),
  ('/project-media/mountainview/hyde-park.webp','mountainview','gallery',3),
  ('/project-media/msquared/masyaf-pool.webp','msquared','gallery',0),
  ('/project-media/msquared/trio-exterior.webp','msquared','gallery',1),
  ('/project-media/msquared/w31-lakeside.webp','msquared','gallery',2),
  ('/project-media/msquared/mist-townhouse.webp','msquared','gallery',3),
  ('/project-media/msquared/b41-hero.webp','msquared','gallery',4),
  ('/project-media/msquared/masyaf-ritsa-night.webp','msquared','gallery',5),
  ('/project-media/ora/brochure/silversands-beach.webp','ora','gallery',0),
  ('/project-media/ora/brochure/zedeast-park.webp','ora','gallery',1),
  ('/project-media/ora/brochure/zedwest-park.webp','ora','gallery',2),
  ('/project-media/ora/brochure/solana-spine.webp','ora','gallery',3),
  ('/project-media/ora/brochure/solanaeast-lake.webp','ora','gallery',4),
  ('/project-media/ora/brochure/zedeast-strip.webp','ora','gallery',5),
  ('/project-media/baghush/beach-aerial.webp','baghush','gallery',0),
  ('/project-media/baghush/lagoon-drone.webp','baghush','gallery',1),
  ('/project-media/baghush/lagoon-firepit.webp','baghush','gallery',2),
  ('/project-media/baghush/botanical-path.webp','baghush','gallery',3),
  ('/project-media/baghush/terrace.webp','baghush','gallery',4),
  ('/project-media/baghush/villa-p1.webp','baghush','gallery',5),
  ('/project-media/beitalbahr/terrace.webp','beitalbahr','gallery',0),
  ('/project-media/beitalbahr/living.webp','beitalbahr','gallery',1),
  ('/project-media/beitalbahr/interior.webp','beitalbahr','gallery',2),
  ('/project-media/beitalbahr/landscape.webp','beitalbahr','gallery',3),
  ('/project-media/beitalbahr/lagoon.webp','beitalbahr','gallery',4),
  ('/project-media/beitalbahr/hotel.webp','beitalbahr','gallery',5)
) as v(path, owner, role, sort_order)
join cms.media_assets a on a.path = v.path
join cms.developers o on lower(o.slug) = lower(v.owner);
