-- Where each image is attached. The path is written once and the owner
-- codes are unnested beside it. A link is only written when both the asset
-- and its owner exist, so a stale reference inserts nothing rather than
-- pointing at the wrong row.
insert into cms.media_links (asset_id, developer_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/project-media/' || 'baghush/beach-aerial.webp','feature',0,array['baghush']),
  ('/project-media/' || 'baghush/lagoon-firepit.webp','feature',3,array['baghush']),
  ('/project-media/' || 'baghush/location.webp','feature',2,array['baghush']),
  ('/project-media/' || 'baghush/masterplan.webp','feature',1,array['baghush']),
  ('/project-media/' || 'beitalbahr/interior.webp','feature',3,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/lagoon.webp','feature',2,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/landscape.webp','feature',1,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/terrace.webp','feature',0,array['beitalbahr']),
  ('/project-media/' || 'marakez/crescent-masterplan.webp','feature',2,array['marakez']),
  ('/project-media/' || 'marakez/d5-residences.webp','feature',1,array['marakez']),
  ('/project-media/' || 'marakez/mall-of-arabia.webp','feature',0,array['marakez']),
  ('/project-media/' || 'marakez/mall-of-arabia.webp','feature',4,array['marakez']),
  ('/project-media/' || 'marakez/ramla-aerial.webp','feature',5,array['marakez']),
  ('/project-media/' || 'marakez/ramla-villa.webp','feature',6,array['marakez']),
  ('/project-media/' || 'marakez/the-park.webp','feature',3,array['marakez']),
  ('/project-media/' || 'modon/connected.webp','feature',1,array['modon']),
  ('/project-media/' || 'modon/mc1.webp','feature',2,array['modon']),
  ('/project-media/' || 'modon/mc2.webp','feature',3,array['modon']),
  ('/project-media/' || 'modon/mc3.webp','feature',4,array['modon']),
  ('/project-media/' || 'modon/mc4.webp','feature',5,array['modon']),
  ('/project-media/' || 'modon/mc5.webp','feature',6,array['modon']),
  ('/project-media/' || 'modon/mc6.webp','feature',7,array['modon']),
  ('/project-media/' || 'modon/partnership.webp','feature',0,array['modon']),
  ('/project-media/' || 'mountainview/aerial.webp','feature',3,array['mountainview']),
  ('/project-media/' || 'mountainview/aliva.webp','feature',26,array['mountainview']),
  ('/project-media/' || 'mountainview/construction-2026.webp','feature',6,array['mountainview']),
  ('/project-media/' || 'mountainview/crysta.webp','feature',30,array['mountainview']),
  ('/project-media/' || 'mountainview/exec-katameya.webp','feature',20,array['mountainview']),
  ('/project-media/' || 'mountainview/gate.webp','feature',1,array['mountainview']),
  ('/project-media/' || 'mountainview/giza-plateau.webp','feature',22,array['mountainview']),
  ('/project-media/' || 'mountainview/grand-valleys.webp','feature',27,array['mountainview']),
  ('/project-media/' || 'mountainview/hyde-park.webp','feature',21,array['mountainview']),
  ('/project-media/' || 'mountainview/icity-newcairo-lagoon.webp','feature',7,array['mountainview']),
  ('/project-media/' || 'mountainview/icity-october-mountain-park.webp','feature',14,array['mountainview']),
  ('/project-media/' || 'mountainview/jirian.webp','feature',29,array['mountainview']),
  ('/project-media/' || 'mountainview/kingsway.webp','feature',28,array['mountainview']),
  ('/project-media/' || 'mountainview/lvls.webp','feature',15,array['mountainview']),
  ('/project-media/' || 'mountainview/mv-raselhikma.webp','feature',24,array['mountainview']),
  ('/project-media/' || 'mountainview/mv-sokhna1.webp','feature',16,array['mountainview']),
  ('/project-media/' || 'mountainview/mv1.webp','feature',18,array['mountainview']),
  ('/project-media/' || 'mountainview/mv11-villas.webp','feature',25,array['mountainview']),
  ('/project-media/' || 'mountainview/mv2.webp','feature',19,array['mountainview']),
  ('/project-media/' || 'mountainview/october-park.webp','feature',5,array['mountainview']),
  ('/project-media/' || 'mountainview/october-park.webp','feature',23,array['mountainview']),
  ('/project-media/' || 'mountainview/park.webp','feature',0,array['mountainview']),
  ('/project-media/' || 'mountainview/raselhikma-lagoon.webp','feature',17,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-1.webp','feature',8,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-2.webp','feature',9,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-3.webp','feature',10,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-4.webp','feature',11,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-5.webp','feature',12,array['mountainview']),
  ('/project-media/' || 'mountainview/timeline-6.webp','feature',13,array['mountainview']),
  ('/project-media/' || 'mountainview/top20.webp','feature',4,array['mountainview']),
  ('/project-media/' || 'mountainview/vision.webp','feature',2,array['mountainview']),
  ('/project-media/' || 'msquared/about-community.webp','feature',0,array['msquared']),
  ('/project-media/' || 'msquared/about-community.webp','feature',5,array['msquared']),
  ('/project-media/' || 'msquared/about-dna.webp','feature',1,array['msquared']),
  ('/project-media/' || 'msquared/about-hospitality.webp','feature',4,array['msquared']),
  ('/project-media/' || 'msquared/about-raselhekma.webp','feature',3,array['msquared']),
  ('/project-media/' || 'msquared/about-values.webp','feature',2,array['msquared']),
  ('/project-media/' || 'ora/brochure/chairman.webp','feature',0,array['ora']),
  ('/project-media/' || 'ora/brochure/silversands-aerial.webp','feature',3,array['ora']),
  ('/project-media/' || 'ora/brochure/silversands-beach.webp','feature',2,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-aerial.webp','feature',11,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-amphitheatre.webp','feature',14,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-spine.webp','feature',12,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-villa.webp','feature',13,array['ora']),
  ('/project-media/' || 'ora/brochure/solanaeast-dusk.webp','feature',16,array['ora']),
  ('/project-media/' || 'ora/brochure/solanaeast-lake.webp','feature',15,array['ora']),
  ('/project-media/' || 'ora/brochure/world.webp','feature',1,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-masterplan.webp','feature',6,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-park.webp','feature',4,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-strip.webp','feature',5,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-location.webp','feature',10,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-masterplan.webp','feature',9,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-park.webp','feature',7,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-towers.webp','feature',8,array['ora']),
  ('/project-media/' || 'orascom/portfolio/andermatt.webp','feature',8,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/byoum.webp','feature',7,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/chbika.webp','feature',14,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/el-gouna-lagoon.webp','feature',0,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/el-gouna.webp','feature',3,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/hawana-salalah.webp','feature',9,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/jebel-sifah.webp','feature',10,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/lustica-bay.webp','feature',11,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/makadi-heights.webp','feature',6,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/marina-night.webp','feature',2,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/o-west.webp','feature',4,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/taba-heights.webp','feature',5,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/uae.webp','feature',12,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/waterfront.webp','feature',1,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/west-carclaze.webp','feature',13,array['orascom']),
  ('/project-media/' || 'sodic/about.webp','feature',0,array['sodic']),
  ('/project-media/' || 'sodic/allegria-residences.webp','feature',7,array['sodic']),
  ('/project-media/' || 'sodic/awards.webp','feature',27,array['sodic']),
  ('/project-media/' || 'sodic/beverly-hills.webp','feature',6,array['sodic']),
  ('/project-media/' || 'sodic/caesar.webp','feature',21,array['sodic']),
  ('/project-media/' || 'sodic/clubs.webp','feature',25,array['sodic']),
  ('/project-media/' || 'sodic/delivery-91.webp','feature',4,array['sodic']),
  ('/project-media/' || 'sodic/eastown.webp','feature',16,array['sodic']),
  ('/project-media/' || 'sodic/edara.webp','feature',24,array['sodic']),
  ('/project-media/' || 'sodic/estates-residences.webp','feature',13,array['sodic']),
  ('/project-media/' || 'sodic/forty-west.webp','feature',9,array['sodic']),
  ('/project-media/' || 'sodic/june.webp','feature',22,array['sodic']),
  ('/project-media/' || 'sodic/kattameya-plaza.webp','feature',20,array['sodic']),
  ('/project-media/' || 'sodic/october-plaza.webp','feature',11,array['sodic']),
  ('/project-media/' || 'sodic/ogami.webp','feature',23,array['sodic']),
  ('/project-media/' || 'sodic/ownership.webp','feature',1,array['sodic']),
  ('/project-media/' || 'sodic/retail.webp','feature',26,array['sodic']),
  ('/project-media/' || 'sodic/six-west.webp','feature',8,array['sodic']),
  ('/project-media/' || 'sodic/sky-condos.webp','feature',18,array['sodic']),
  ('/project-media/' || 'sodic/sodic-east.webp','feature',19,array['sodic']),
  ('/project-media/' || 'sodic/sodic-west.webp','feature',2,array['sodic']),
  ('/project-media/' || 'sodic/sodic-west.webp','feature',5,array['sodic']),
  ('/project-media/' || 'sodic/the-estates.webp','feature',12,array['sodic']),
  ('/project-media/' || 'sodic/v-residences.webp','feature',17,array['sodic']),
  ('/project-media/' || 'sodic/villette.webp','feature',15,array['sodic']),
  ('/project-media/' || 'sodic/vye-karmell.webp','feature',14,array['sodic']),
  ('/project-media/' || 'sodic/westown-residences.webp','feature',10,array['sodic']),
  ('/project-media/' || 'sodic/where-we-operate.webp','feature',3,array['sodic']),
  ('/project-media/' || 'sumou/ap5-0.webp','feature',4,array['sumou']),
  ('/project-media/' || 'sumou/lo-s.webp','feature',1,array['sumou']),
  ('/project-media/' || 'sumou/st-01.webp','feature',0,array['sumou']),
  ('/project-media/' || 'sumou/st-02.webp','feature',3,array['sumou']),
  ('/project-media/' || 'sumou/st-03.webp','feature',2,array['sumou']),
  ('/project-media/' || 'baghush/beach-aerial.webp','gallery',0,array['baghush']),
  ('/project-media/' || 'baghush/botanical-path.webp','gallery',3,array['baghush']),
  ('/project-media/' || 'baghush/lagoon-drone.webp','gallery',1,array['baghush']),
  ('/project-media/' || 'baghush/lagoon-firepit.webp','gallery',2,array['baghush']),
  ('/project-media/' || 'baghush/terrace.webp','gallery',4,array['baghush']),
  ('/project-media/' || 'baghush/villa-p1.webp','gallery',5,array['baghush']),
  ('/project-media/' || 'beitalbahr/hotel.webp','gallery',5,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/interior.webp','gallery',2,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/lagoon.webp','gallery',4,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/landscape.webp','gallery',3,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/living.webp','gallery',1,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/terrace.webp','gallery',0,array['beitalbahr']),
  ('/project-media/' || 'marakez/aeon-tower.webp','gallery',2,array['marakez']),
  ('/project-media/' || 'marakez/crescent-park.webp','gallery',0,array['marakez']),
  ('/project-media/' || 'marakez/d5-campus.webp','gallery',3,array['marakez']),
  ('/project-media/' || 'marakez/mall-of-arabia.webp','gallery',1,array['marakez']),
  ('/project-media/' || 'marakez/the-park.webp','gallery',4,array['marakez']),
  ('/project-media/' || 'modon/m1.webp','gallery',0,array['modon']),
  ('/project-media/' || 'modon/m2.webp','gallery',1,array['modon']),
  ('/project-media/' || 'modon/m3.webp','gallery',2,array['modon']),
  ('/project-media/' || 'modon/m4.webp','gallery',3,array['modon']),
  ('/project-media/' || 'modon/m5.webp','gallery',4,array['modon']),
  ('/project-media/' || 'modon/m6.webp','gallery',5,array['modon']),
  ('/project-media/' || 'mountainview/crysta.webp','gallery',2,array['mountainview']),
  ('/project-media/' || 'mountainview/hyde-park.webp','gallery',3,array['mountainview']),
  ('/project-media/' || 'mountainview/jirian.webp','gallery',1,array['mountainview']),
  ('/project-media/' || 'mountainview/park.webp','gallery',0,array['mountainview']),
  ('/project-media/' || 'msquared/b41-hero.webp','gallery',4,array['msquared']),
  ('/project-media/' || 'msquared/masyaf-pool.webp','gallery',0,array['msquared']),
  ('/project-media/' || 'msquared/masyaf-ritsa-night.webp','gallery',5,array['msquared']),
  ('/project-media/' || 'msquared/mist-townhouse.webp','gallery',3,array['msquared']),
  ('/project-media/' || 'msquared/trio-exterior.webp','gallery',1,array['msquared']),
  ('/project-media/' || 'msquared/w31-lakeside.webp','gallery',2,array['msquared']),
  ('/project-media/' || 'ora/brochure/silversands-beach.webp','gallery',0,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-spine.webp','gallery',3,array['ora']),
  ('/project-media/' || 'ora/brochure/solanaeast-lake.webp','gallery',4,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-park.webp','gallery',1,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-strip.webp','gallery',5,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-park.webp','gallery',2,array['ora']),
  ('/project-media/' || 'orascom/portfolio/andermatt.webp','gallery',5,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/byoum.webp','gallery',4,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/chbika.webp','gallery',11,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/el-gouna.webp','gallery',0,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/hawana-salalah.webp','gallery',6,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/jebel-sifah.webp','gallery',7,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/lustica-bay.webp','gallery',8,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/makadi-heights.webp','gallery',3,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/o-west.webp','gallery',1,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/taba-heights.webp','gallery',2,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/uae.webp','gallery',9,array['orascom']),
  ('/project-media/' || 'orascom/portfolio/west-carclaze.webp','gallery',10,array['orascom']),
  ('/project-media/' || 'sodic/caesar.webp','gallery',4,array['sodic']),
  ('/project-media/' || 'sodic/eastown.webp','gallery',2,array['sodic']),
  ('/project-media/' || 'sodic/ogami.webp','gallery',5,array['sodic']),
  ('/project-media/' || 'sodic/sodic-west.webp','gallery',0,array['sodic']),
  ('/project-media/' || 'sodic/the-estates.webp','gallery',1,array['sodic']),
  ('/project-media/' || 'sodic/villette.webp','gallery',3,array['sodic']),
  ('/project-media/' || 'sumou/ap2-03.webp','gallery',4,array['sumou']),
  ('/project-media/' || 'sumou/ap5-0.webp','gallery',2,array['sumou']),
  ('/project-media/' || 'sumou/of4.webp','gallery',5,array['sumou']),
  ('/project-media/' || 'sumou/st-01.webp','gallery',1,array['sumou']),
  ('/project-media/' || 'sumou/st-02.webp','gallery',3,array['sumou']),
  ('/project-media/' || 'sumou/st-03.webp','gallery',0,array['sumou']),
  ('/logos/al-ahly-sabbour.webp','logo',0,array['alahlysabbour']),
  ('/logos/al-marasem.webp','logo',0,array['marasem']),
  ('/logos/beit-al-bahr.webp','logo',0,array['beitalbahr']),
  ('/logos/city-edge.webp','logo',0,array['cityedge']),
  ('/logos/emaar-misr.webp','logo',0,array['emaarmisr']),
  ('/logos/hassan-allam.webp','logo',0,array['hassanallam']),
  ('/logos/hyde-park.webp','logo',0,array['hydepark']),
  ('/logos/il-cazar.webp','logo',0,array['ilcazar']),
  ('/logos/inertia.webp','logo',0,array['inertia']),
  ('/logos/la-vista.webp','logo',0,array['lavista']),
  ('/logos/lmd.webp','logo',0,array['lmd']),
  ('/logos/m-squared.webp','logo',0,array['msquared']),
  ('/logos/madinet-masr.webp','logo',0,array['madinetmasr']),
  ('/logos/marakez.webp','logo',0,array['marakez']),
  ('/logos/marsa-baghush.webp','logo',0,array['baghush']),
  ('/logos/misr-italia.webp','logo',0,array['misritalia']),
  ('/logos/modon.webp','logo',0,array['modon']),
  ('/logos/mountain-view.webp','logo',0,array['mountainview']),
  ('/logos/ora.webp','logo',0,array['ora']),
  ('/logos/orascom.webp','logo',0,array['orascom']),
  ('/logos/palm-hills.webp','logo',0,array['palmhills']),
  ('/logos/qatari-diar.webp','logo',0,array['qataridiar']),
  ('/logos/saudi-egyptian.webp','logo',0,array['saudiegyptian']),
  ('/logos/sodic.webp','logo',0,array['sodic']),
  ('/logos/sumou.webp','logo',0,array['sumou']),
  ('/logos/tatweer-misr.webp','logo',0,array['tatweer']),
  ('/logos/tmg.webp','logo',0,array['tmg']),
  ('/logos/travco.webp','logo',0,array['travco']),
  ('/project-media/' || 'baghush/masterplan-coded.webp','masterplan',0,array['baghush']),
  ('/project-media/' || 'beitalbahr/masterplan.webp','masterplan',0,array['beitalbahr']),
  ('/project-media/' || 'marakez/d5-masterplan.webp','masterplan',0,array['marakez']),
  ('/project-media/' || 'modon/masterplan.webp','masterplan',0,array['modon']),
  ('/project-media/' || 'mountainview/projects-map.webp','masterplan',0,array['mountainview']),
  ('/project-media/' || 'ora/brochure/silversands-aerial.webp','masterplan',0,array['ora']),
  ('/project-media/' || 'sodic/where-we-operate.webp','masterplan',0,array['sodic']),
  ('/project-media/' || 'sumou/mp-s.webp','masterplan',0,array['sumou'])
) as v(path, role, sort_order, owners)
cross join lateral unnest(v.owners) as owner_code
join cms.media_assets a on a.path = v.path
join cms.developers o on lower(o.slug) = lower(owner_code);
