-- Where each image is attached. The path is written once and the owner
-- codes are unnested beside it. A link is only written when both the asset
-- and its owner exist, so a stale reference inserts nothing rather than
-- pointing at the wrong row.
insert into cms.media_links (asset_id, project_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/project-media/' || 'allegria/standalone.webp','cover',0,array['allegria']),
  ('/project-media/' || 'baghush/lagoon-firepit.webp','cover',0,array['marsa-baghush']),
  ('/project-media/' || 'beitalbahr/units/V1-01-H-d1.webp','cover',0,array['bab-hills']),
  ('/project-media/' || 'beitalbahr/units/ch1-03-sh.webp','cover',0,array['bab-shores']),
  ('/project-media/' || 'beitalbahr/units/v1-01-hills.webp','cover',0,array['bab-hills-by-the-sea']),
  ('/project-media/' || 'beitalbahr/units/v1-01-rays.webp','cover',0,array['bab-rays']),
  ('/project-media/' || 'beitalbahr/units/v1-01-roo.webp','cover',0,array['bab-roots']),
  ('/project-media/' || 'caesar/villa.webp','cover',0,array['caesar-north-coast']),
  ('/project-media/' || 'eastown/apartment.webp','cover',0,array['eastown']),
  ('/project-media/' || 'hassan-allam/ap-of1-r1.webp','cover',0,array['ampm-swanlake']),
  ('/project-media/' || 'hassan-allam/gl-ap1-r1.webp','cover',0,array['the-great-lawn']),
  ('/project-media/' || 'hassan-allam/pc-ap1-r1.webp','cover',0,array['park-central']),
  ('/project-media/' || 'hassan-allam/px-ap1-r1.webp','cover',0,array['phonix-swanlake']),
  ('/project-media/' || 'hassan-allam/sl-ap1-r1.webp','cover',0,array['swan-lake-west']),
  ('/project-media/' || 'hassan-allam/vl-th1-r1.webp','cover',0,array['the-valleys']),
  ('/project-media/' || 'hero/promenade.webp','cover',0,array['ramla-ras-el-hekma']),
  ('/project-media/' || 'june/standalone-june.webp','cover',0,array['june-north-coast']),
  ('/project-media/' || 'lmd/cover-one-ninety.webp','cover',0,array['one-ninety']),
  ('/project-media/' || 'lmd/cover-stei8ht-eastmed.webp','cover',0,array['stei8ht-eastmed']),
  ('/project-media/' || 'lmd/cover-stei8ht-eastside.webp','cover',0,array['stei8ht-eastside']),
  ('/project-media/' || 'lmd/cover-stei8ht-there.webp','cover',0,array['stei8ht-there']),
  ('/project-media/' || 'lmd/cover-three-sixty.webp','cover',0,array['three-sixty']),
  ('/project-media/' || 'lmd/cover-zoya.webp','cover',0,array['zoya']),
  ('/project-media/' || 'marakez/shams-soma/hero.webp','cover',0,array['shams-soma']),
  ('/project-media/' || 'marakez/units/ap1-d-04.webp','cover',0,array['district-5']),
  ('/project-media/' || 'marakez/units/v2-cr-0.webp','cover',0,array['crescent-walk']),
  ('/project-media/' || 'modon/ap1-bp-03.webp','cover',0,array['beach-plaza-premium']),
  ('/project-media/' || 'modon/ap1-bpl-0.webp','cover',0,array['beach-plaza-luxury']),
  ('/project-media/' || 'modon/ap1-lh-0.webp','cover',0,array['lighthouse-village-luxury']),
  ('/project-media/' || 'modon/ap1-lhu-0.webp','cover',0,array['lighthouse-village-ultra-luxury']),
  ('/project-media/' || 'modon/ap2-bl-0.webp','cover',0,array['modon-boulevard']),
  ('/project-media/' || 'modon/th-wd-01.webp','cover',0,array['wadi-east']),
  ('/project-media/' || 'modon/v1-mon-0.webp','cover',0,array['montage']),
  ('/project-media/' || 'mountainview/crysta.webp','cover',0,array['crysta-north-coast']),
  ('/project-media/' || 'mountainview/grand-valleys.webp','cover',0,array['grand-valleys']),
  ('/project-media/' || 'mountainview/icity-october-mountain-park.webp','cover',0,array['icity-october']),
  ('/project-media/' || 'mountainview/jirian.webp','cover',0,array['jirian']),
  ('/project-media/' || 'mountainview/kingsway.webp','cover',0,array['kingsway-october']),
  ('/project-media/' || 'mountainview/lvls.webp','cover',0,array['lvls-north-coast']),
  ('/project-media/' || 'mountainview/mv11-villas.webp','cover',0,array['mountain-view-11']),
  ('/project-media/' || 'mountainview/plage.webp','cover',0,array['plage-north-coast']),
  ('/project-media/' || 'msquared/b41-hero.webp','cover',0,array['41-business-district']),
  ('/project-media/' || 'msquared/masyaf-pool.webp','cover',0,array['masyaf-ras-alhekma']),
  ('/project-media/' || 'msquared/trio-exterior.webp','cover',0,array['trio-new-cairo']),
  ('/project-media/' || 'msquared/units/ap1-west-0.webp','cover',0,array['31-west-october']),
  ('/project-media/' || 'msquared/units/town1-0.webp','cover',0,array['mist-new-cairo']),
  ('/project-media/' || 'ogami/apartment.webp','cover',0,array['ogami-north-coast']),
  ('/project-media/' || 'ora/ap1-cr-0.webp','cover',0,array['silversands-crystalline']),
  ('/project-media/' || 'ora/ap1-se-0.webp','cover',0,array['solana-east']),
  ('/project-media/' || 'ora/ap1-ss-0.webp','cover',0,array['silversands-silvertown']),
  ('/project-media/' || 'ora/ap1-z-0.webp','cover',0,array['zed-east']),
  ('/project-media/' || 'ora/du1-em-0.webp','cover',0,array['zed-east-emerald']),
  ('/project-media/' || 'ora/st-zw-0.webp','cover',0,array['zed-west']),
  ('/project-media/' || 'ora/v8-0.webp','cover',0,array['solana-west']),
  ('/project-media/' || 'orascom/ledge-valley/hero.webp','cover',0,array['ledge-valley']),
  ('/project-media/' || 'orascom/siyal/lagoon-beach.webp','cover',0,array['siyal']),
  ('/project-media/' || 'qataridiar/alam-al-roum/city.webp','cover',0,array['alam-al-roum']),
  ('/project-media/' || 'ramla/units/ap-a-03.webp','cover',0,array['aeon']),
  ('/project-media/' || 'sodic-east/apartment.webp','cover',0,array['sodic-east']),
  ('/project-media/' || 'sumou/st-03.webp','cover',0,array['sumou-boulevard']),
  ('/project-media/' || 'tatweer/ap1-bl-0.webp','cover',0,array['bloomfields']),
  ('/project-media/' || 'tatweer/ch-dp-0.webp','cover',0,array['d-bay']),
  ('/project-media/' || 'tatweer/ch-sl-0.webp','cover',0,array['salt']),
  ('/project-media/' || 'tatweer/f-0.webp','cover',0,array['fouka-bay']),
  ('/project-media/' || 'tatweer/r-0.webp','cover',0,array['rivers']),
  ('/project-media/' || 'tatweer/th-sc-0.webp','cover',0,array['scenes']),
  ('/project-media/' || 'tatweer/tm-sv-il-0.webp','cover',0,array['il-monte-galala']),
  ('/project-media/' || 'the-estates/villa.webp','cover',0,array['the-estates-zayed']),
  ('/project-media/' || 'villette/i-villa.webp','cover',0,array['villette']),
  ('/logos/projects/allegria.webp','logo',0,array['allegria']),
  ('/logos/projects/caesar.webp','logo',0,array['caesar-north-coast']),
  ('/logos/projects/eastown.webp','logo',0,array['eastown']),
  ('/logos/projects/june.webp','logo',0,array['june-north-coast']),
  ('/logos/projects/ogami.webp','logo',0,array['ogami-north-coast']),
  ('/logos/projects/sodic-east.webp','logo',0,array['sodic-east']),
  ('/logos/projects/the-estates.webp','logo',0,array['the-estates-zayed']),
  ('/logos/projects/villette.webp','logo',0,array['villette'])
) as v(path, role, sort_order, owners)
cross join lateral unnest(v.owners) as owner_code
join cms.media_assets a on a.path = v.path
join cms.projects o on lower(o.slug) = lower(owner_code);
