-- Where each image is attached. The path is written once and the owner
-- codes are unnested beside it. A link is only written when both the asset
-- and its owner exist, so a stale reference inserts nothing rather than
-- pointing at the wrong row.
insert into cms.media_links (asset_id, developer_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/project-media/' || 'baghush/beach-aerial.webp','gallery',0,array['baghush']),
  ('/project-media/' || 'baghush/botanical-path.webp','gallery',3,array['baghush']),
  ('/project-media/' || 'baghush/lagoon-drone.webp','gallery',1,array['baghush']),
  ('/project-media/' || 'baghush/lagoon-firepit.webp','gallery',2,array['baghush']),
  ('/project-media/' || 'baghush/terrace.webp','gallery',4,array['baghush']),
  ('/project-media/' || 'baghush/villa-p1.webp','gallery',5,array['baghush']),
  ('/project-media/' || 'beitalbahr/hotel.webp','gallery',5,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/interior.webp','gallery',2,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/lagoon.webp','gallery',4,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/landscape.webp','gallery',3,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/living.webp','gallery',1,array['beitalbahr']),
  ('/project-media/' || 'beitalbahr/terrace.webp','gallery',0,array['beitalbahr']),
  ('/project-media/' || 'marakez/aeon-tower.webp','gallery',2,array['marakez']),
  ('/project-media/' || 'marakez/crescent-park.webp','gallery',0,array['marakez']),
  ('/project-media/' || 'marakez/d5-campus.webp','gallery',3,array['marakez']),
  ('/project-media/' || 'marakez/mall-of-arabia.webp','gallery',1,array['marakez']),
  ('/project-media/' || 'marakez/the-park.webp','gallery',4,array['marakez']),
  ('/project-media/' || 'modon/m1.webp','gallery',0,array['modon']),
  ('/project-media/' || 'modon/m2.webp','gallery',1,array['modon']),
  ('/project-media/' || 'modon/m3.webp','gallery',2,array['modon']),
  ('/project-media/' || 'modon/m4.webp','gallery',3,array['modon']),
  ('/project-media/' || 'modon/m5.webp','gallery',4,array['modon']),
  ('/project-media/' || 'modon/m6.webp','gallery',5,array['modon']),
  ('/project-media/' || 'mountainview/crysta.webp','gallery',2,array['mountainview']),
  ('/project-media/' || 'mountainview/hyde-park.webp','gallery',3,array['mountainview']),
  ('/project-media/' || 'mountainview/jirian.webp','gallery',1,array['mountainview']),
  ('/project-media/' || 'mountainview/park.webp','gallery',0,array['mountainview']),
  ('/project-media/' || 'msquared/b41-hero.webp','gallery',4,array['msquared']),
  ('/project-media/' || 'msquared/masyaf-pool.webp','gallery',0,array['msquared']),
  ('/project-media/' || 'msquared/masyaf-ritsa-night.webp','gallery',5,array['msquared']),
  ('/project-media/' || 'msquared/mist-townhouse.webp','gallery',3,array['msquared']),
  ('/project-media/' || 'msquared/trio-exterior.webp','gallery',1,array['msquared']),
  ('/project-media/' || 'msquared/w31-lakeside.webp','gallery',2,array['msquared']),
  ('/project-media/' || 'ora/brochure/silversands-beach.webp','gallery',0,array['ora']),
  ('/project-media/' || 'ora/brochure/solana-spine.webp','gallery',3,array['ora']),
  ('/project-media/' || 'ora/brochure/solanaeast-lake.webp','gallery',4,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-park.webp','gallery',1,array['ora']),
  ('/project-media/' || 'ora/brochure/zedeast-strip.webp','gallery',5,array['ora']),
  ('/project-media/' || 'ora/brochure/zedwest-park.webp','gallery',2,array['ora']),
  ('/project-media/' || 'sodic/caesar.webp','gallery',4,array['sodic']),
  ('/project-media/' || 'sodic/eastown.webp','gallery',2,array['sodic']),
  ('/project-media/' || 'sodic/ogami.webp','gallery',5,array['sodic']),
  ('/project-media/' || 'sodic/sodic-west.webp','gallery',0,array['sodic']),
  ('/project-media/' || 'sodic/the-estates.webp','gallery',1,array['sodic']),
  ('/project-media/' || 'sodic/villette.webp','gallery',3,array['sodic']),
  ('/project-media/' || 'sumou/ap2-03.webp','gallery',4,array['sumou']),
  ('/project-media/' || 'sumou/ap5-0.webp','gallery',2,array['sumou']),
  ('/project-media/' || 'sumou/of4.webp','gallery',5,array['sumou']),
  ('/project-media/' || 'sumou/st-01.webp','gallery',1,array['sumou']),
  ('/project-media/' || 'sumou/st-02.webp','gallery',3,array['sumou']),
  ('/project-media/' || 'sumou/st-03.webp','gallery',0,array['sumou']),
  ('/logos/al-ahly-sabbour.webp','logo',0,array['alahlysabbour']),
  ('/logos/al-marasem.webp','logo',0,array['marasem']),
  ('/logos/beit-al-bahr.webp','logo',0,array['beitalbahr']),
  ('/logos/city-edge.webp','logo',0,array['cityedge']),
  ('/logos/emaar-misr.webp','logo',0,array['emaarmisr']),
  ('/logos/hassan-allam.webp','logo',0,array['hassanallam']),
  ('/logos/hyde-park.webp','logo',0,array['hydepark']),
  ('/logos/il-cazar.webp','logo',0,array['ilcazar']),
  ('/logos/inertia.webp','logo',0,array['inertia']),
  ('/logos/la-vista.webp','logo',0,array['lavista']),
  ('/logos/lmd.webp','logo',0,array['lmd']),
  ('/logos/m-squared.webp','logo',0,array['msquared']),
  ('/logos/madinet-masr.webp','logo',0,array['madinetmasr']),
  ('/logos/marakez.webp','logo',0,array['marakez']),
  ('/logos/marsa-baghush.webp','logo',0,array['baghush']),
  ('/logos/misr-italia.webp','logo',0,array['misritalia']),
  ('/logos/modon.webp','logo',0,array['modon']),
  ('/logos/mountain-view.webp','logo',0,array['mountainview']),
  ('/logos/ora.webp','logo',0,array['ora']),
  ('/logos/orascom.webp','logo',0,array['orascom']),
  ('/logos/palm-hills.webp','logo',0,array['palmhills']),
  ('/logos/qatari-diar.webp','logo',0,array['qataridiar']),
  ('/logos/saudi-egyptian.webp','logo',0,array['saudiegyptian']),
  ('/logos/sodic.webp','logo',0,array['sodic']),
  ('/logos/sumou.webp','logo',0,array['sumou']),
  ('/logos/tatweer-misr.webp','logo',0,array['tatweer']),
  ('/logos/tmg.webp','logo',0,array['tmg'])
) as v(path, role, sort_order, owners)
cross join lateral unnest(v.owners) as owner_code
join cms.media_assets a on a.path = v.path
join cms.developers o on lower(o.slug) = lower(owner_code);
