-- Where each image is attached. A link is only written when both the
-- asset and its owner exist, so a stale reference inserts nothing rather
-- than pointing at the wrong row.
insert into cms.media_links (asset_id, project_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/project-media/ramla/units/ap-a-03.webp','aeon','cover',0),
  ('/project-media/marakez/units/ap1-d-04.webp','district-5','cover',0),
  ('/project-media/marakez/units/v2-cr-0.webp','crescent-walk','cover',0),
  ('/project-media/qataridiar/alam-al-roum/city.webp','alam-al-roum','cover',0),
  ('/project-media/msquared/b41-hero.webp','41-business-district','cover',0),
  ('/project-media/msquared/masyaf-pool.webp','masyaf-ras-alhekma','cover',0),
  ('/project-media/msquared/trio-exterior.webp','trio-new-cairo','cover',0),
  ('/project-media/msquared/units/town1-0.webp','mist-new-cairo','cover',0),
  ('/project-media/msquared/units/ap1-west-0.webp','31-west-october','cover',0),
  ('/project-media/ora/ap1-z-0.webp','zed-east','cover',0),
  ('/project-media/ora/du1-em-0.webp','zed-east-emerald','cover',0),
  ('/project-media/ora/st-zw-0.webp','zed-west','cover',0),
  ('/project-media/ora/v8-0.webp','solana-west','cover',0),
  ('/project-media/ora/ap1-se-0.webp','solana-east','cover',0),
  ('/project-media/ora/ap1-cr-0.webp','silversands-crystalline','cover',0),
  ('/project-media/ora/ap1-ss-0.webp','silversands-silvertown','cover',0),
  ('/project-media/beitalbahr/units/ch1-03-sh.webp','bab-shores','cover',0),
  ('/project-media/beitalbahr/units/v1-01-roo.webp','bab-roots','cover',0),
  ('/project-media/beitalbahr/units/v1-01-rays.webp','bab-rays','cover',0),
  ('/project-media/beitalbahr/units/v1-01-hills.webp','bab-hills-by-the-sea','cover',0),
  ('/project-media/beitalbahr/units/V1-01-H-d1.webp','bab-hills','cover',0),
  ('/project-media/baghush/lagoon-firepit.webp','marsa-baghush','cover',0),
  ('/project-media/sumou/st-03.webp','sumou-boulevard','cover',0),
  ('/project-media/modon/ap1-bp-03.webp','beach-plaza-premium','cover',0),
  ('/project-media/modon/ap1-bpl-0.webp','beach-plaza-luxury','cover',0),
  ('/project-media/modon/ap1-lh-0.webp','lighthouse-village-luxury','cover',0),
  ('/project-media/modon/ap1-lhu-0.webp','lighthouse-village-ultra-luxury','cover',0),
  ('/project-media/modon/th-wd-01.webp','wadi-east','cover',0),
  ('/project-media/modon/v1-mon-0.webp','montage','cover',0),
  ('/project-media/modon/ap2-bl-0.webp','modon-boulevard','cover',0),
  ('/project-media/tatweer/tm-sv-il-0.webp','il-monte-galala','cover',0),
  ('/project-media/tatweer/ap1-bl-0.webp','bloomfields','cover',0),
  ('/project-media/tatweer/ch-sl-0.webp','salt','cover',0),
  ('/project-media/tatweer/r-0.webp','rivers','cover',0),
  ('/project-media/tatweer/f-0.webp','fouka-bay','cover',0),
  ('/project-media/tatweer/ch-dp-0.webp','d-bay','cover',0),
  ('/project-media/tatweer/th-sc-0.webp','scenes','cover',0),
  ('/project-media/villette/i-villa.webp','villette','cover',0),
  ('/project-media/sodic-east/apartment.webp','sodic-east','cover',0),
  ('/project-media/eastown/apartment.webp','eastown','cover',0),
  ('/project-media/allegria/standalone.webp','allegria','cover',0),
  ('/project-media/ogami/apartment.webp','ogami-north-coast','cover',0),
  ('/project-media/caesar/villa.webp','caesar-north-coast','cover',0),
  ('/project-media/june/standalone-june.webp','june-north-coast','cover',0),
  ('/project-media/the-estates/villa.webp','the-estates-zayed','cover',0),
  ('/project-media/hero/promenade.webp','ramla-ras-el-hekma','cover',0),
  ('/project-media/lmd/cover-three-sixty.webp','three-sixty','cover',0),
  ('/project-media/lmd/cover-one-ninety.webp','one-ninety','cover',0),
  ('/project-media/lmd/cover-zoya.webp','zoya','cover',0),
  ('/project-media/lmd/cover-stei8ht-eastmed.webp','stei8ht-eastmed','cover',0),
  ('/project-media/lmd/cover-stei8ht-there.webp','stei8ht-there','cover',0),
  ('/project-media/lmd/cover-stei8ht-eastside.webp','stei8ht-eastside','cover',0),
  ('/project-media/hassan-allam/px-ap1-r1.webp','phonix-swanlake','cover',0),
  ('/project-media/hassan-allam/ap-of1-r1.webp','ampm-swanlake','cover',0),
  ('/project-media/hassan-allam/vl-th1-r1.webp','the-valleys','cover',0),
  ('/project-media/hassan-allam/pc-ap1-r1.webp','park-central','cover',0),
  ('/project-media/hassan-allam/gl-ap1-r1.webp','the-great-lawn','cover',0),
  ('/project-media/hassan-allam/sl-ap1-r1.webp','swan-lake-west','cover',0),
  ('/project-media/mountainview/mv11-villas.webp','mountain-view-11','cover',0),
  ('/project-media/mountainview/grand-valleys.webp','grand-valleys','cover',0),
  ('/project-media/mountainview/icity-october-mountain-park.webp','icity-october','cover',0),
  ('/project-media/mountainview/kingsway.webp','kingsway-october','cover',0),
  ('/project-media/mountainview/jirian.webp','jirian','cover',0),
  ('/project-media/mountainview/lvls.webp','lvls-north-coast','cover',0),
  ('/project-media/mountainview/plage.webp','plage-north-coast','cover',0),
  ('/project-media/mountainview/crysta.webp','crysta-north-coast','cover',0),
  ('villette.png','villette','logo',0),
  ('sodic-east.png','sodic-east','logo',0),
  ('eastown.png','eastown','logo',0),
  ('allegria.png','allegria','logo',0),
  ('ogami.png','ogami-north-coast','logo',0),
  ('caesar.png','caesar-north-coast','logo',0),
  ('june.png','june-north-coast','logo',0),
  ('the-estates.png','the-estates-zayed','logo',0)
) as v(path, owner, role, sort_order)
join cms.media_assets a on a.path = v.path
join cms.projects o on lower(o.slug) = lower(v.owner);
