-- Where each image is attached. The path is written once and the owner
-- codes are unnested beside it. A link is only written when both the asset
-- and its owner exist, so a stale reference inserts nothing rather than
-- pointing at the wrong row.
insert into cms.media_links (asset_id, project_id, role, sort_order)
select a.id, o.id, v.role::cms.media_role, v.sort_order
from (values
  ('/project-media/' || 'orascom/ledge-valley/chalet-street.webp','gallery',9,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/design.webp','gallery',3,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/floating.webp','gallery',10,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/hero.webp','gallery',0,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/island.webp','gallery',7,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/lagoon.webp','gallery',2,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/neighbourhood.webp','gallery',6,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/outdoor.webp','gallery',11,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/park.webp','gallery',5,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/poolside.webp','gallery',4,array['ledge-valley']),
  ('/project-media/' || 'orascom/ledge-valley/promenade.webp','gallery',1,array['ledge-valley']),
  ('/project-media/' || 'orascom/makadi-heights/renders/courtyard-homes.webp','gallery',1,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/garden-home.webp','gallery',5,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/neighbourhood.webp','gallery',3,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/pool-terraces.webp','gallery',0,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/poolside-homes.webp','gallery',2,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/promenade.webp','gallery',9,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/shaded-terrace.webp','gallery',8,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/street-villa.webp','gallery',6,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/terrace-villa.webp','gallery',7,array['makadi-heights']),
  ('/project-media/' || 'orascom/makadi-heights/renders/townhomes.webp','gallery',4,array['makadi-heights']),
  ('/project-media/' || 'orascom/siyal/boutique-villa.webp','gallery',6,array['siyal']),
  ('/project-media/' || 'orascom/siyal/courtyard-villa.webp','gallery',4,array['siyal']),
  ('/project-media/' || 'orascom/siyal/courtyard.webp','gallery',1,array['siyal']),
  ('/project-media/' || 'orascom/siyal/grand-villa.webp','gallery',5,array['siyal']),
  ('/project-media/' || 'orascom/siyal/interior.webp','gallery',8,array['siyal']),
  ('/project-media/' || 'orascom/siyal/lagoon-beach.webp','gallery',0,array['siyal']),
  ('/project-media/' || 'orascom/siyal/lagoon-park.webp','gallery',2,array['siyal']),
  ('/project-media/' || 'orascom/siyal/signature-villa.webp','gallery',3,array['siyal']),
  ('/project-media/' || 'orascom/siyal/social.webp','gallery',9,array['siyal']),
  ('/project-media/' || 'orascom/siyal/townhouse.webp','gallery',7,array['siyal']),
  ('/project-media/' || 'orascom/siyal/walkability.webp','gallery',10,array['siyal']),
  ('/project-media/' || 'qataridiar/alam-al-roum/arch.webp','gallery',8,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/beach.webp','gallery',5,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/boulevard.webp','gallery',4,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/city.webp','gallery',0,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/coast.webp','gallery',1,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/golf.webp','gallery',10,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/lagoon.webp','gallery',6,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/marina.webp','gallery',9,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/masterplan.webp','gallery',3,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/spine.webp','gallery',7,array['alam-al-roum']),
  ('/project-media/' || 'qataridiar/alam-al-roum/story.webp','gallery',2,array['alam-al-roum']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p01.webp','gallery',0,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p03.webp','gallery',1,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p06.webp','gallery',2,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p08.webp','gallery',3,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p10.webp','gallery',4,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p11.webp','gallery',5,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p13.webp','gallery',6,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p14.webp','gallery',7,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p16.webp','gallery',8,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p18.webp','gallery',9,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p20.webp','gallery',10,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p22.webp','gallery',11,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p23.webp','gallery',12,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p24.webp','gallery',13,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p25.webp','gallery',14,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p26.webp','gallery',15,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p31.webp','gallery',16,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p33.webp','gallery',17,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p35.webp','gallery',18,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p36.webp','gallery',19,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p40.webp','gallery',20,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p45.webp','gallery',21,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p50.webp','gallery',22,array['caesar-north-coast']),
  ('/project-media/' || 'sodic/caesar-north-coast/brochure/p59.webp','gallery',23,array['caesar-north-coast']),
  ('/project-media/' || 'travco/makadina/p16.webp','gallery',0,array['makadina']),
  ('/project-media/' || 'travco/makadina/p17.webp','gallery',1,array['makadina']),
  ('/project-media/' || 'travco/makadina/p18.webp','gallery',2,array['makadina']),
  ('/project-media/' || 'travco/makadina/p19.webp','gallery',3,array['makadina']),
  ('/project-media/' || 'travco/makadina/p20.webp','gallery',4,array['makadina']),
  ('/project-media/' || 'travco/makadina/p21.webp','gallery',5,array['makadina']),
  ('/project-media/' || 'travco/makadina/p24.webp','gallery',6,array['makadina']),
  ('/project-media/' || 'travco/makadina/p27.webp','gallery',7,array['makadina']),
  ('/project-media/' || 'travco/marina-gate/p13.webp','gallery',0,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p14.webp','gallery',1,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p15.webp','gallery',2,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p16.webp','gallery',3,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p17.webp','gallery',4,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p19.webp','gallery',5,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p25.webp','gallery',6,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p26.webp','gallery',7,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p31.webp','gallery',8,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p32.webp','gallery',9,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p37.webp','gallery',10,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p38.webp','gallery',11,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p45.webp','gallery',12,array['marina-gate']),
  ('/project-media/' || 'travco/marina-gate/p46.webp','gallery',13,array['marina-gate']),
  ('/project-media/' || 'travco/ras-soma/apartments.webp','gallery',15,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/bay.webp','gallery',2,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/beach-cabana.webp','gallery',3,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/beach-club.webp','gallery',7,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/beach-villa.webp','gallery',12,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/beachfront-villa.webp','gallery',11,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/cover.webp','gallery',0,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/lagoon-beach-club.webp','gallery',8,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/marina.webp','gallery',6,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/oasis-lagoon-park.webp','gallery',9,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/quad-chalet.webp','gallery',14,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/residences-aerial.webp','gallery',1,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/shore-villa.webp','gallery',13,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/the-town.webp','gallery',4,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/the-village.webp','gallery',5,array['ras-soma']),
  ('/project-media/' || 'travco/ras-soma/wadi-park.webp','gallery',10,array['ras-soma']),
  ('/project-media/' || 'elmasria/isola-centra/location.webp','location',0,array['isola-centra']),
  ('/project-media/' || 'elmasria/isola-quattro/location.webp','location',0,array['isola-quattro']),
  ('/project-media/' || 'lmd/brochure/one-ninety-location.webp','location',0,array['one-ninety']),
  ('/project-media/' || 'lmd/zoya/location.webp','location',0,array['zoya']),
  ('/project-media/' || 'orascom/makadi-heights/plans/location.webp','location',0,array['makadi-heights']),
  ('/project-media/' || 'travco/ras-soma/location.webp','location',0,array['ras-soma']),
  ('/logos/projects/caesar.webp','logo',0,array['caesar-north-coast']),
  ('/logos/projects/june.webp','logo',0,array['june-north-coast']),
  ('/logos/projects/ogami.webp','logo',0,array['ogami-north-coast']),
  ('/logos/projects/sodic-east.webp','logo',0,array['sodic-east']),
  ('/logos/projects/the-estates.webp','logo',0,array['the-estates-zayed']),
  ('/logos/projects/villette.webp','logo',0,array['villette']),
  ('/project-media/' || 'elmasria/isola-centra/masterplan.webp','masterplan',0,array['isola-centra']),
  ('/project-media/' || 'elmasria/isola-quattro/masterplan.webp','masterplan',0,array['isola-quattro']),
  ('/project-media/' || 'emaarmisr/marassi-red-sea/units/masterplan.webp','masterplan',0,array['marassi-red-sea']),
  ('/project-media/' || 'lmd/one-ninety/masterplan.webp','masterplan',0,array['one-ninety']),
  ('/project-media/' || 'lmd/three-sixty/masterplan-aerial.webp','masterplan',0,array['three-sixty']),
  ('/project-media/' || 'lmd/zoya/masterplan.webp','masterplan',0,array['zoya']),
  ('/project-media/' || 'marakez/shams-soma/masterplan.webp','masterplan',0,array['shams-soma']),
  ('/project-media/' || 'msquared/masyaf-masterplan.webp','masterplan',0,array['masyaf-ras-alhekma']),
  ('/project-media/' || 'msquared/mist-masterplan.webp','masterplan',0,array['mist-new-cairo']),
  ('/project-media/' || 'msquared/trio-masterplan.webp','masterplan',0,array['trio-new-cairo']),
  ('/project-media/' || 'msquared/w31-masterplan.webp','masterplan',0,array['31-west-october']),
  ('/project-media/' || 'orascom/ledge-valley/masterplan.webp','masterplan',0,array['ledge-valley']),
  ('/project-media/' || 'orascom/makadi-heights/plans/masterplan.webp','masterplan',0,array['makadi-heights']),
  ('/project-media/' || 'orascom/siyal/masterplan.webp','masterplan',0,array['siyal']),
  ('/project-media/' || 'qataridiar/alam-al-roum/masterplan.webp','masterplan',0,array['alam-al-roum']),
  ('/project-media/' || 'travco/ras-soma/masterplan.webp','masterplan',0,array['ras-soma'])
) as v(path, role, sort_order, owners)
cross join lateral unnest(v.owners) as owner_code
join cms.media_assets a on a.path = v.path
join cms.projects o on lower(o.slug) = lower(owner_code);
