-- 84 projects. Every one is `published`: they are all live on the site today,
-- and a migration must not quietly unpublish anything.
insert into cms.projects (slug, name_en, name_ar, developer_id, location_id, stage,
  description_en, description_ar, price_from, down_payment_pct, instalment_years,
  delivery_label, finishing_en, finishing_ar, unit_types_en, unit_types_ar,
  tags_en, tags_ar, status, published_at)
select v.slug, v.name_en, v.name_ar, dev.id, loc.id, v.stage::cms.project_stage,
  v.description_en, v.description_ar, v.price_from, v.dp, v.years,
  v.delivery_label, v.finishing_en, v.finishing_ar, v.unit_types_en, v.unit_types_ar,
  v.tags_en, v.tags_ar, 'published', now()
from (values
  ('fouka-bay','Fouka Bay','فوكا باي','tatweer','sahel','primary','Tatweer Misr’s North Coast resort near Ras El Hekma, known for terraced beachfront and turquoise swimmable lagoons. Developer-direct primary units.','منتجع تطوير مصر على الساحل الشمالي قرب رأس الحكمة، معروف بالشاطئ المتدرّج والبحيرات الفيروزية للسباحة. وحدات أولية من المطوّر مباشرة.',13900000,5,9,'2030','Fully finished','تشطيب كامل','Chalet · Apartment','شاليه · شقة','{"North Coast","Turquoise lagoons"}','{"الساحل الشمالي","بحيرات فيروزية"}'),
  ('vinci-capital','Vinci','فينشي','misritalia','capital','primary','Misr Italia’s green, technology-enabled community in the New Administrative Capital, with generous landscaping and amenities. Developer-direct primary units.','مجتمع مصر إيطاليا الأخضر المزوّد بالتقنيات بالعاصمة الإدارية الجديدة، بمساحات خضراء ومرافق واسعة. وحدات أولية من المطوّر مباشرة.',6500000,10,8,'2028','Semi-finished','نصف تشطيب','Apartment · Villa','شقة · فيلا','{"New Capital","Green living"}','{"العاصمة الإدارية","معيشة خضراء"}'),
  ('masyaf-ras-alhekma','Masyaf Ras Alhekma','مصياف رأس الحكمة','msquared','raselhekma','primary','Inspired by Greek architecture, where floating seascapes and natural simplicity live indoors, Masyaf Ras Alhekma stretches over 112 feddans of land lapping a pristine 730-metre beachfront on the Mediterranean shore. Master planned by M squared, it lifts its homes onto elevated platforms so every owner gets an equal view. Its own downtown carries Ritsa, the Barten restaurant, the Peppermint wellbeing centre and the Marmarica boutique cabanas.','مستوحى من العمارة اليونانية حيث تعيش المشاهد البحرية والبساطة الطبيعية في الداخل، يمتد مصياف رأس الحكمة على ١١٢ فداناً بواجهة بحرية بكر بطول ٧٣٠ متراً على شاطئ المتوسط. وضعت إم سكويرد مخططه العام ورفعت منازله على منصات متدرّجة ليحصل كل مالك على إطلالة متساوية. ويضم داون تاون خاصاً به يحوي «ريتسا» ومطعم «بارتن» ومركز «بيبرمنت» للعافية وكابانات «مرماريكا» البوتيكية.',12190419,10,10,'2028–2030',null,null,'Chalet · Duplex · Penthouse · Townhouse · Villa','شاليه · دوبلكس · بنتهاوس · تاون هاوس · فيلا','{"Ras Al Hekma","112 feddans","730 m beachfront"}','{"رأس الحكمة","١١٢ فدان","٧٣٠ م واجهة بحرية"}'),
  ('trio-new-cairo','TRIO','تريو','msquared','newcairo','primary','A signature boutique community on 35.5 acres of verdant land at the heart of New Cairo. TRIO is characterised by a “three villas per complex” concept with hanging gardens and flying pools, and each duplex has its own garden and maximum privacy. Three phases sit around a central spine carrying a reading work station, a yoga garden, a meditation zone and a kids’ play zone.','مجتمع بوتيكي مميّز على ٣٥٫٥ فدان من الأرض الخضراء في قلب القاهرة الجديدة. يتميّز «تريو» بمفهوم «ثلاث فيلات لكل مجمّع» بحدائق معلّقة وحمامات سباحة طائرة، ولكل دوبلكس حديقته الخاصة وأقصى درجات الخصوصية. وتلتفّ ثلاث مراحل حول محور مركزي يضم ركن قراءة وعمل، وحديقة يوجا، ومنطقة تأمّل، ومنطقة لعب للأطفال.',11637891,10,10,'2027–2028',null,null,'Apartment · Duplex · Townhouse · Penthouse','شقة · دوبلكس · تاون هاوس · بنتهاوس','{"New Cairo","35.5 acres","Three villas per complex"}','{"القاهرة الجديدة","٣٥٫٥ فدان","ثلاث فيلات لكل مجمّع"}'),
  ('mist-new-cairo','MIST','ميست','msquared','newcairo','launch','In East Cairo’s Golden Square, MIST rises as a new-generation mixed-use development spanning 45 feddans, with over 18,000 square metres of lakes and water paths flowing through the land and more than 80 per cent of the residential space kept green. MIST is not a place you escape to. It is a place you live within, pass through, and engage with fully — a passage, a lifestyle artery and a destination all at once. Rather than rigid zones, the community unfolds in intuitive layers: serene homes flow alongside water and greenery, while a commercial promenade brings daily vibrance, and a public plaza at the centre ties it together. The name was chosen for its relevance to motion, transformation and fluidity.','في جولدن سكوير بشرق القاهرة يقوم «ميست» كمشروع متعدد الاستخدامات من جيل جديد على ٤٥ فداناً، بأكثر من ١٨٬٠٠٠ متر مربع من البحيرات والممرات المائية تجري في أرضه، وأكثر من ٨٠٪ من المساحة السكنية مُبقاة خضراء. و«ميست» ليس مكاناً تهرب إليه، بل مكان تعيش داخله وتمرّ به وتنخرط فيه بالكامل — ممرّ وشريان لايف ستايل ووجهة في آن. وبدلاً من المناطق الجامدة، ينكشف المجتمع في طبقات بديهية: منازل هادئة تنساب بمحاذاة الماء والخضرة، وبروميناد تجاري يمنح الحياة اليومية حيويتها، وبلازا عامة في المركز تربط كل شيء. واختير الاسم لصلته بالحركة والتحوّل والانسيابية.',17602921,5,10,'2030',null,null,'Apartment · Penthouse · Townhouse','شقة · بنتهاوس · تاون هاوس','{"East Cairo Golden Square","45 feddans","18,000 m² of lakes"}','{"جولدن سكوير شرق القاهرة","٤٥ فدان","١٨٬٠٠٠ م² بحيرات"}'),
  ('31-west-october','31 WEST','٣١ ويست','msquared','october','primary','31 WEST epitomises refined living within 31 acres at one of the most exclusive locations in 6th of October, where every detail is curated to exude exclusivity and sophistication. From grand water features and inspiring designs to landscaped surroundings and the first-of-its-kind Senior Executive Suites, the project stands as a testament to timeless elegance and elite living.','يجسّد «٣١ ويست» السكن الراقي على ٣١ فداناً في أحد أكثر مواقع ٦ أكتوبر تميّزاً، حيث كل تفصيلة منتقاة لتفيض تفرّداً ورقيّاً. ومن المسطحات المائية الكبرى والتصاميم الملهمة إلى المحيط المنسّق والأجنحة التنفيذية الأولى من نوعها، يقف المشروع شاهداً على الأناقة الخالدة والحياة الصفوية.',13237120,5,10,'2030','Apartments fully finished · single homes semi-finished','الشقق كاملة التشطيب · المنازل المستقلة نصف تشطيب','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"6th of October","31 acres","570 units"}','{"٦ أكتوبر","٣١ فدان","٥٧٠ وحدة"}'),
  ('41-business-district','41 Business District','٤١ بيزنس ديستريكت','msquared','newcairo','primary','A commercial landmark at the heart of the Kattameya Ring Road, connecting multiple districts of the city. 41 Business District is an innovative, multipurpose concept that blends cutting-edge office and clinic spaces with commercial luxuries in one building — a bank, café, restaurant, gym, furniture, barber, sports, jewellery and market at street level.','معلم تجاري في قلب الطريق الدائري بالقطامية، يربط عدة أحياء بالمدينة. «٤١ بيزنس ديستريكت» مفهوم مبتكر متعدد الاستخدامات يمزج مساحات المكاتب والعيادات الحديثة مع رفاهيات تجارية في مبنى واحد — بنك ومقهى ومطعم وجيم وأثاث وحلاق ورياضة ومجوهرات وسوق على مستوى الشارع.',13962832,10,8,'2029',null,null,'Office','مكتب','{"Kattameya Ring Road","Commercial landmark"}','{"الطريق الدائري القطامية","معلم تجاري"}'),
  ('zed-east','ZED East','زيد إيست','ora','newcairo','launch','ZED East by ORA in New Cairo — 8 primary unit types from the developer''s own price list: apartment, loft, studio. From 65 m² and EGP 8,900,000, on a 10% down payment over 10 years, handover 2027–2030.','زيد إيست من أورا في القاهرة الجديدة — ٨ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شقة، لوفت، استوديو. من ٦٥ م² و٨٬٩٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٢٧–٢٠٣٠.',8900000,10,10,'2027–2030',null,null,'Apartment · Loft · Studio','شقة · لوفت · استوديو','{"New Cairo","8 units","65–300 m²"}','{"القاهرة الجديدة","٨ وحدات","٦٥–٣٠٠ م²"}'),
  ('zed-east-emerald','ZED East Emerald','زيد إيست إميرالد','ora','newcairo','launch','ZED East Emerald by ORA in New Cairo — 6 primary unit types from the developer''s own price list: duplex, fourplex, townhouse, standalone villa. From 174 m² and EGP 27,000,000, on a 10% down payment over 10 years, handover 2030.','زيد إيست إميرالد من أورا في القاهرة الجديدة — ٦ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: دوبلكس، فوربلكس، تاون هاوس، فيلا مستقلة. من ١٧٤ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',27000000,10,10,'2030',null,null,'Duplex · Fourplex · Townhouse · Standalone Villa','دوبلكس · فوربلكس · تاون هاوس · فيلا مستقلة','{"New Cairo","6 units","174–290 m²"}','{"القاهرة الجديدة","٦ وحدات","١٧٤–٢٩٠ م²"}'),
  ('zed-west','ZED West','زيد ويست','ora','zayed','launch','ZED West by ORA in New Zayed — 7 primary unit types from the developer''s own price list: studio, apartment. From 60 m² and EGP 9,000,000, on a 10% down payment over 10 years, handover 2030.','زيد ويست من أورا في زايد الجديدة — ٧ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: استوديو، شقة. من ٦٠ م² و٩٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',9000000,10,10,'2030',null,null,'Studio · Apartment','استوديو · شقة','{"New Zayed","7 units","60–219 m²"}','{"زايد الجديدة","٧ وحدات","٦٠–٢١٩ م²"}'),
  ('solana-west','Solana West','سولانا ويست','ora','zayed','launch','Solana West by ORA in New Zayed — 16 primary unit types from the developer''s own price list: villa, townhouse, twin house, apartment, loft, duplex, penthouse. From 126 m² and EGP 15,800,000, on a 10% down payment over 10 years, handover 2030.','سولانا ويست من أورا في زايد الجديدة — ١٦ نوع وحدة أولية من قائمة أسعار المطوّر نفسه: فيلا، تاون هاوس، توين هاوس، شقة، لوفت، دوبلكس، بنتهاوس. من ١٢٦ م² و١٥٬٨٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',15800000,10,10,'2030',null,null,'Villa · Townhouse · Twin House · Apartment · Loft · Duplex · Penthouse','فيلا · تاون هاوس · توين هاوس · شقة · لوفت · دوبلكس · بنتهاوس','{"New Zayed","16 units","126–337 m²"}','{"زايد الجديدة","١٦ وحدة","١٢٦–٣٣٧ م²"}'),
  ('solana-east','Solana East','سولانا إيست','ora','newcairo','launch','Solana East by ORA in New Cairo — 5 primary unit types from the developer''s own price list: apartment, twin house, villa. From 99 m² and EGP 13,900,000, on a 10% down payment over 8 years, handover 2030.','سولانا إيست من أورا في القاهرة الجديدة — ٥ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شقة، توين هاوس، فيلا. من ٩٩ م² و١٣٬٩٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ٨ سنوات، والتسليم ٢٠٣٠.',13900000,10,8,'2030',null,null,'Apartment · Twin House · Villa','شقة · توين هاوس · فيلا','{"New Cairo","5 units","99–369 m²"}','{"القاهرة الجديدة","٥ وحدات","٩٩–٣٦٩ م²"}'),
  ('silversands-crystalline','Silversands Crystalline','سيلفر ساندز كريستالين','ora','sahel','launch','Silversands Crystalline by ORA in Sidi Heneish — 9 primary unit types from the developer''s own price list: duplex, chalet, twin house, villa. From 160 m² and EGP 27,000,000, on a 15% down payment over 8 years, handover 2030.','سيلفر ساندز كريستالين من أورا في سيدي حنيش — ٩ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: دوبلكس، شاليه، توين هاوس، فيلا. من ١٦٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٥٪ على ٨ سنوات، والتسليم ٢٠٣٠.',27000000,15,8,'2030',null,null,'Duplex · Chalet · Twin House · Villa','دوبلكس · شاليه · توين هاوس · فيلا','{"Sidi Heneish","9 units","160–380 m²"}','{"سيدي حنيش","٩ وحدات","١٦٠–٣٨٠ م²"}'),
  ('silversands-silvertown','Silversands Silvertown','سيلفر ساندز سيلفر تاون','ora','sahel','launch','Silversands Silvertown by ORA in Sidi Heneish — 7 primary unit types from the developer''s own price list: chalet, townhouse, villa. From 150 m² and EGP 27,000,000, on a 10% down payment over 10 years, handover 2030.','سيلفر ساندز سيلفر تاون من أورا في سيدي حنيش — ٧ أنواع وحدات أولية من قائمة أسعار المطوّر نفسه: شاليه، تاون هاوس، فيلا. من ١٥٠ م² و٢٧٬٠٠٠٬٠٠٠ جنيه، بمقدم ١٠٪ على ١٠ سنوات، والتسليم ٢٠٣٠.',27000000,10,10,'2030',null,null,'Chalet · Townhouse · Villa','شاليه · تاون هاوس · فيلا','{"Sidi Heneish","7 units","150–250 m²"}','{"سيدي حنيش","٧ وحدات","١٥٠–٢٥٠ م²"}'),
  ('village-de-la-capitale','Village de la Capitale','فيلاج دي لا كابيتال','palmhills','capital','primary','A 290-feddan Palm Hills community with apartments, townhouses and villas, water features, sports courts and club houses. Developer-direct primary units on a 12-year plan.','مجتمع بالم هيلز على ٢٩٠ فداناً يضم شققاً وتاون هاوس وفيلات مع نوافير مائية وملاعب رياضية وكلوب هاوس. وحدات أولية من المطوّر مباشرة بتقسيط ١٢ سنة.',6400000,1.5,12,'2029','Core & shell','خرسانة على المحارة','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"New Capital","290 feddans"}','{"العاصمة الإدارية","٢٩٠ فدان"}'),
  ('palm-hills-new-cairo','Palm Hills New Cairo','بالم هيلز القاهرة الجديدة','palmhills','newcairo','primary','Palm Hills’ established 500-feddan New Cairo community — the fully finished Cleo apartments plus villas, a 40-feddan Palm Hills club, hotel and international school. Developer-direct primary units.','مجتمع بالم هيلز المتكامل على ٥٠٠ فدان بالقاهرة الجديدة — شقق Cleo كاملة التشطيب وفيلات ونادي بالم هيلز على ٤٠ فداناً وفندق ومدرسة دولية. وحدات أولية من المطوّر مباشرة.',10400000,5,8,'2027','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Villa','شقة · فيلا','{"New Cairo","500 feddans"}','{"القاهرة الجديدة","٥٠٠ فدان"}'),
  ('97-hills','97 Hills','٩٧ هيلز','palmhills','newcairo','primary','A 97-feddan Palm Hills community in New Cairo built around lagoons and a community centre, with family houses, townhouses, twin houses and villas. Developer-direct primary units over 10 years.','مجتمع بالم هيلز على ٩٧ فداناً بالقاهرة الجديدة حول البحيرات ومركز مجتمعي، ببيوت عائلية وتاون هاوس وتوين هاوس وفيلات. وحدات أولية من المطوّر مباشرة بتقسيط ١٠ سنوات.',25800000,5,10,'2029','Core & shell / fully finished','خرسانة / تشطيب كامل','Townhouse · Twin house · Villa','تاون هاوس · توين هاوس · فيلا','{"New Cairo","Lagoons"}','{"القاهرة الجديدة","بحيرات"}'),
  ('palmet-new-cairo','Palmet New Cairo','بالمت القاهرة الجديدة','palmhills','newcairo','primary','A 100-feddan Palm Hills commercial destination in New Cairo on Palm Hills Drive — retail, offices, banks, clinics and pharmacies. Developer-direct primary units.','وجهة بالم هيلز التجارية على ١٠٠ فدان بالقاهرة الجديدة على Palm Hills Drive — محلات ومكاتب وبنوك وعيادات وصيدليات. وحدات أولية من المطوّر مباشرة.',13000000,5,8,'2027','Core & shell','خرسانة على المحارة','Retail · Offices · Clinics','محلات · مكاتب · عيادات','{"New Cairo","Commercial"}','{"القاهرة الجديدة","تجاري"}'),
  ('px-new-cairo','PX','بي إكس','palmhills','newcairo','primary','PX is Palm Hills’ 370-feddan New Cairo district — G+3 apartments, townhouses and villas with a Palm Hills club and commercial hub. Developer-direct primary units, delivery 2030.','PX هو حي بالم هيلز على ٣٧٠ فداناً بالقاهرة الجديدة — شقق أرضي+٣ وتاون هاوس وفيلات مع نادي بالم هيلز ومنطقة تجارية. وحدات أولية من المطوّر مباشرة، التسليم ٢٠٣٠.',13500000,5,8,'2030','Core & shell / fully finished','خرسانة / تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"New Cairo","370 feddans"}','{"القاهرة الجديدة","٣٧٠ فدان"}'),
  ('jirian-zayed','Palm Hills Jirian','بالم هيلز جيريان','palmhills','zayed','primary','A 360-feddan Palm Hills community in West Cairo with Nile views — fully finished apartments, townhouses and villas, hotels and a commercial spine. Developer-direct primary units.','مجتمع بالم هيلز على ٣٦٠ فداناً بغرب القاهرة بإطلالات على النيل — شقق وتاون هاوس وفيلات كاملة التشطيب وفنادق ومحور تجاري. وحدات أولية من المطوّر مباشرة.',7800000,5,8,'2029','Fully finished','تشطيب كامل','Apartment · Townhouse · Villa','شقة · تاون هاوس · فيلا','{"Sheikh Zayed","Nile views"}','{"الشيخ زايد","إطلالة على النيل"}'),
  ('hacienda-blue','Hacienda Blue','هاسيندا بلو','palmhills','raselhekma','primary','Palm Hills’ 118-acre beachfront resort at Ras El Hekma (Km 166) with lagoons, parks and a 400m beach — G+1 apartments, cabins, townhouses and water villas. Developer-direct primary units.','منتجع بالم هيلز الشاطئي على ١١٨ فداناً برأس الحكمة (كيلو ١٦٦) ببحيرات وحدائق وشاطئ ٤٠٠ متر — شقق أرضي+١ وكبائن وتاون هاوس وفيلات مائية. وحدات أولية من المطوّر مباشرة.',19600000,2.5,12,'2030','Fully finished (no kitchen/AC)','تشطيب كامل (بدون مطبخ وتكييف)','Apartment · Cabin · Townhouse · Villa','شقة · كابين · تاون هاوس · فيلا','{"Ras El Hekma","400m beachfront"}','{"رأس الحكمة","واجهة بحرية ٤٠٠م"}')
) as v(slug, name_en, name_ar, dev_slug, area_slug, stage, description_en, description_ar,
       price_from, dp, years, delivery_label, finishing_en, finishing_ar,
       unit_types_en, unit_types_ar, tags_en, tags_ar)
join cms.developers dev on dev.slug = v.dev_slug
join cms.locations  loc on loc.slug = v.area_slug
on conflict (slug) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar,
  developer_id = excluded.developer_id, location_id = excluded.location_id,
  stage = excluded.stage, description_en = excluded.description_en,
  description_ar = excluded.description_ar, price_from = excluded.price_from,
  down_payment_pct = excluded.down_payment_pct, instalment_years = excluded.instalment_years,
  delivery_label = excluded.delivery_label, finishing_en = excluded.finishing_en,
  finishing_ar = excluded.finishing_ar, unit_types_en = excluded.unit_types_en,
  unit_types_ar = excluded.unit_types_ar, tags_en = excluded.tags_en, tags_ar = excluded.tags_ar;
